sc_somanet-base: module_fwupdate/flash_somanet.xc File Reference
flash_somanet.xc File Reference
Somanet Firmware Update implemtation.
#include <platform.h>
#include <stdio.h>
#include <flash_somanet.h>
#include <print.h>
Macros
#define START_FLASH 12;
#define END_FLASH 26;
#define FLASH 1;
#define IDLE 0;
Functions
int flash_connect ()
void flash_setup (int factory)
void chipReset (void)
int check_file_access (chanend foe_comm, unsigned address, chanend reset_out)
void firmware_update (chanend foe_comm, chanend foe_signal, chanend reset)
Firmware update function This thread must be on CORE 0 only.
void get_file (chanend foe_out, char filename[])
firmware update ///
void reset_cores (chanend sig_in, chanend sig_out)
void reset_last_core (chanend sig_in)
Variables
on stdcore [0]
on PORT_SPI_SS
on PORT_SPI_CLK
on PORT_SPI_MOSI
on XS1_CLKBLK_2
int write_state = IDLE
int start_flash = START_FLASH
int end_flash = END_FLASH
int flash1 = FLASH
Detailed Description
Somanet Firmware Update implemtation.
Copyright (c) 2014, Synapticon GmbH All rights reserved. Author: Frank Jeschke jesch.nosp@m.ke@f.nosp@m.jes.d.nosp@m.e & Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file flash_somanet.xc.
Macro Definition Documentation
#define END_FLASH 26;
Definition at line 47 of file flash_somanet.xc.
#define FLASH 1;
Definition at line 48 of file flash_somanet.xc.
#define IDLE 0;
Definition at line 49 of file flash_somanet.xc.
Referenced by check_file_access().
#define START_FLASH 12;
Definition at line 46 of file flash_somanet.xc.
Function Documentation
int check_file_access (chanend foe_comm, unsigned address, chanend reset_out)
Definition at line 90 of file flash_somanet.xc.
References BUFFER_SIZE, flash1, flash_buf_end(), flash_buffer(), flash_setup(), IDLE, start_flash, and write_state.
Referenced by firmware_update().
void chipReset (void)
Definition at line 81 of file flash_somanet.xc.
Referenced by reset_cores(), and reset_last_core().
void firmware_update (chanend foe_comm, chanend foe_signal, chanend reset)
Firmware update function This thread must be on CORE 0 only.
Definition at line 179 of file flash_somanet.xc.
References check_file_access().
int flash_connect ()
Definition at line 70 of file flash_somanet.xc.
References fl_connect().
Referenced by flash_setup().
void flash_setup (int factory)
Definition at line 55 of file flash_write.c.
References fl_setProtection(), flash_connect(), and flash_erase().
Referenced by check_file_access().
void get_file (chanend foe_out, char filename[])
firmware update ///
Definition at line 236 of file flash_somanet.xc.
void reset_cores (chanend sig_in, chanend sig_out)
Definition at line 255 of file flash_somanet.xc.
References chipReset().
void reset_last_core (chanend sig_in)
Definition at line 275 of file flash_somanet.xc.
References chipReset().
Variable Documentation
int end_flash = END_FLASH
Definition at line 64 of file flash_somanet.xc.
int flash1 = FLASH
Definition at line 65 of file flash_somanet.xc.
Referenced by check_file_access().
on PORT_SPI_CLK
Definition at line 56 of file flash_somanet.xc.
on PORT_SPI_MOSI
Definition at line 56 of file flash_somanet.xc.
on PORT_SPI_SS
Definition at line 56 of file flash_somanet.xc.
int start_flash = START_FLASH
Definition at line 63 of file flash_somanet.xc.
Referenced by check_file_access().
on stdcore[0]
Definition at line 56 of file flash_somanet.xc.
Referenced by main().
int write_state = IDLE
Definition at line 62 of file flash_somanet.xc.
Referenced by check_file_access().
on XS1_CLKBLK_2
Definition at line 56 of file flash_somanet.xc.