sc_somanet-base: app_linux_fwupdate/src/nicdrv.h File Reference
nicdrv.h File Reference
Headerfile for nicdrv.c.
Functions
int ec_setupnic (const char *ifname, int secondary)
int ec_closenic (void)
void ec_setupheader (void *p)
void ec_setbufstat (uint8 idx, int bufstat)
uint8 ec_getindex (void)
int ec_outframe (uint8 idx, int sock)
int ec_outframe_red (uint8 idx)
int ec_waitinframe (uint8 idx, int timeout)
int ec_srconfirm (uint8 idx, int timeout)
Variables
ec_bufT ec_rxbuf [EC_MAXBUF]
ec_bufT ec_txbuf [EC_MAXBUF]
ec_bufT ec_txbuf2
int ec_txbuflength [EC_MAXBUF]
int ec_txbuflength2
int ec_incnt
int ec_errcnt
int ec_redstate
int hlp_txtime
int hlp_rxtime
int sockhandle
int sockhandle2
const uint16 priMAC [3]
const uint16 secMAC [3]
Detailed Description
Headerfile for nicdrv.c.
Definition in file nicdrv.h.
Function Documentation
int ec_closenic (void)
Close sockets used
Returns
0
Definition at line 254 of file nicdrv.c.
References sockhandle, and sockhandle2.
Referenced by ec_close().
uint8 ec_getindex (void)
Get new frame identifier index and allocate corresponding rx buffer.
Returns
new index.
Definition at line 283 of file nicdrv.c.
References EC_BUF_ALLOC, EC_BUF_EMPTY, ec_getindex_mutex, EC_MAXBUF, and ec_rxbufstat.
Referenced by ec_APRD(), ec_APWR(), ec_ARMW(), ec_BRD(), ec_BWR(), ec_FPRD(), ec_FPWR(), ec_FRMW(), ec_LRD(), ec_LRW(), ec_LRWDC(), ec_LWR(), and ec_send_processdata_group().
int ec_outframe (uint8 idx, int stacknumber)
Transmit buffer over socket (non blocking).
Parameters
[in] idx = index in tx buffer array
[in] stacknumber = 0=Primary 1=Secondary stack
Returns
socket send result
Definition at line 331 of file nicdrv.c.
References EC_BUF_TX, ec_stackT::rxbufstat, ec_stackT::sock, ec_stackT::txbuf, and ec_stackT::txbuflength.
Referenced by ec_outframe_red().
int ec_outframe_red (uint8 idx)
Transmit buffer over socket (non blocking).
Parameters
[in] idx = index in tx buffer array
Returns
socket send result
Definition at line 348 of file nicdrv.c.
References EC_BUF_TX, ec_outframe(), ec_redstate, ec_tx_mutex, ec_txbuf, ec_txbuf2, ec_txbuflength2, ECT_RED_NONE, ETH_HEADERSIZE, PACKED::index, priMAC, PACKED::sa1, secMAC, and sockhandle2.
Referenced by ec_send_processdata_group(), and ec_srconfirm().
void ec_setbufstat (uint8 idx, int bufstat)
Set rx buffer status.
Parameters
[in] idx = index in buffer array
[in] bufstat = status to set
Definition at line 320 of file nicdrv.c.
References ec_rxbufstat.
Referenced by ec_APRD(), ec_APWR(), ec_ARMW(), ec_BRD(), ec_BWR(), ec_FPRD(), ec_FPWR(), ec_FRMW(), ec_LRD(), ec_LRW(), ec_LRWDC(), ec_LWR(), ec_receive_processdata_group(), ec_srconfirm(), and ec_waitinframe().
void ec_setupheader (void * p)
Fill buffer with ethernet header structure. Destination MAC is allways broadcast. Ethertype is allways ETH_P_ECAT.
Parameters
[out] p = buffer
Definition at line 267 of file nicdrv.c.
References PACKED::da0, PACKED::da1, PACKED::da2, ETH_P_ECAT, PACKED::etype, priMAC, PACKED::sa0, PACKED::sa1, and PACKED::sa2.
Referenced by ec_setupnic().
int ec_setupnic (const char * ifname, int secondary)
Basic setup to connect NIC to socket.
Parameters
[in] ifname = Name of NIC device, f.e. "eth0"
[in] secondary = if >0 then use secondary stack instead of primary
Returns
>0 if succeeded
Definition at line 188 of file nicdrv.c.
References EC_BUF_EMPTY, ec_errcnt, ec_incnt, EC_MAXBUF, ec_redstate, ec_rxbufstat, ec_setupheader(), ec_txbuf, ec_txbuf2, ECT_RED_DOUBLE, ECT_RED_NONE, ETH_P_ECAT, sockhandle, and sockhandle2.
Referenced by ec_init(), and ec_init_redundant().
int ec_srconfirm (uint8 idx, int timeout)
Blocking send and recieve frame function. Used for non processdata frames. A datagram is build into a frame and transmitted via this function. It waits for an answer and returns the workcounter. The function retries if time is left and the result is WKC=0 or no frame received.
The function calls ec_outframe_red() and ec_waitinframe_red().
Parameters
[in] idx = index of frame
[in] timeout = timeout in us
Returns
Workcounter or EC_NOFRAME
Definition at line 615 of file nicdrv.c.
References EC_BUF_EMPTY, EC_NOFRAME, ec_outframe_red(), ec_setbufstat(), EC_TIMEOUTRET, hlp_rxtime, and hlp_txtime.
Referenced by ec_APRD(), ec_APWR(), ec_ARMW(), ec_BRD(), ec_BWR(), ec_FPRD(), ec_FPWR(), ec_FRMW(), ec_LRD(), ec_LRW(), ec_LRWDC(), and ec_LWR().
int ec_waitinframe (uint8 idx, int timeout)
Blocking receive frame function. Calls ec_waitinframe_red().
Parameters
[in] idx = requested index of frame
[in] timeout = timeout in us
Returns
Workcounter if a frame is found with corresponding index, otherwise EC_NOFRAME.
Definition at line 585 of file nicdrv.c.
References EC_BUF_EMPTY, EC_NOFRAME, and ec_setbufstat().
Referenced by ec_receive_processdata_group().
Variable Documentation
int ec_errcnt
global error packet counter, ie non EtherCAT packets
Definition at line 156 of file nicdrv.c.
Referenced by ec_inframe(), and ec_setupnic().
int ec_incnt
global rx packet counter, counts only EtherCAT packets
Definition at line 154 of file nicdrv.c.
Referenced by ec_inframe(), and ec_setupnic().
int ec_redstate
current redundancy state
Definition at line 158 of file nicdrv.c.
Referenced by ec_outframe_red(), and ec_setupnic().
ec_bufT ec_rxbuf[EC_MAXBUF]
primary rx buffers
Definition at line 113 of file nicdrv.c.
Referenced by ec_APRD(), ec_ARMW(), ec_BRD(), ec_FPRD(), ec_FRMW(), ec_LRD(), ec_LRW(), ec_LRWDC(), and ec_receive_processdata_group().
ec_bufT ec_txbuf[EC_MAXBUF]
transmit buffers
Definition at line 133 of file nicdrv.c.
Referenced by ec_APRD(), ec_APWR(), ec_ARMW(), ec_BRD(), ec_BWR(), ec_FPRD(), ec_FPWR(), ec_FRMW(), ec_LRD(), ec_LRW(), ec_LRWDC(), ec_LWR(), ec_outframe_red(), ec_send_processdata_group(), and ec_setupnic().
ec_bufT ec_txbuf2
temporary tx buffer
Definition at line 137 of file nicdrv.c.
Referenced by ec_init_redundant(), ec_outframe_red(), and ec_setupnic().
int ec_txbuflength[EC_MAXBUF]
transmit buffer lenghts
Definition at line 135 of file nicdrv.c.
Referenced by ec_adddatagram(), and ec_setupdatagram().
int ec_txbuflength2
temporary tx buffer length
Definition at line 139 of file nicdrv.c.
Referenced by ec_init_redundant(), and ec_outframe_red().
int hlp_rxtime
global helper var ri count time used in rx socket
Definition at line 163 of file nicdrv.c.
Referenced by ec_srconfirm().
int hlp_txtime
global helper var to count time used in tx socket
Definition at line 161 of file nicdrv.c.
Referenced by ec_srconfirm().
const uint16 priMAC[3]
Primary source MAC address used for EtherCAT. This address is not the MAC address used from the NIC. EtherCAT does not care about MAC addressing, but it is used here to differentiate the route the packet traverses through the EtherCAT segment. This is needed to find out the packet flow in redundant configurations.
Definition at line 170 of file nicdrv.c.
Referenced by ec_outframe_red(), and ec_setupheader().
const uint16 secMAC[3]
Secondary source MAC address used for EtherCAT.
Definition at line 172 of file nicdrv.c.
Referenced by ec_init_redundant(), and ec_outframe_red().
int sockhandle
primary socket handle
Definition at line 142 of file nicdrv.c.
Referenced by ec_closenic(), and ec_setupnic().
int sockhandle2
secondary socket handle
Definition at line 144 of file nicdrv.c.
Referenced by ec_closenic(), ec_outframe_red(), and ec_setupnic().