sc_somanet-base: module_fwupdate/device_access.xc File Reference
device_access.xc File Reference
#include <xclib.h>
#include <xs1.h>
#include "device_access.h"
Functions
int fl_int_spiMasterInit (void)
int fl_int_spiInit (int div)
unsigned int fl_int_issueShortCommand (unsigned char cmd, unsigned int addr, unsigned int addrSize, unsigned int dummySize, unsigned int dataSize)
int fl_int_getBusyStatus (const fl_DeviceSpec &flashAccess)
unsigned int fl_int_getFullStatus (const fl_DeviceSpec &flashAccess)
void fl_int_waitWhileWriting (const fl_DeviceSpec &flashAccess)
int fl_int_programPageAsync (const fl_DeviceSpec &flashAccess, unsigned int pageAddress, const unsigned char data[])
int fl_int_programPage (const fl_DeviceSpec &flashAccess, unsigned int pageAddress, const unsigned char data[])
int fl_int_readBytes (const fl_DeviceSpec &flashAccess, unsigned pageAddress, unsigned char data[], unsigned int numBytes)
Variables
fl_PortHolderStruct g_portHolder
int g_fl_int_doWaitForCompletion
Function Documentation
int fl_int_getBusyStatus (const fl_DeviceSpec & flashAccess)
Definition at line 165 of file device_access.xc.
References fl_int_issueShortCommand().
Referenced by fl_int_waitWhileWriting().
unsigned int fl_int_getFullStatus (const fl_DeviceSpec & flashAccess)
Definition at line 171 of file device_access.xc.
References fl_int_issueShortCommand().
unsigned int fl_int_issueShortCommand (unsigned char cmd, unsigned int addr, unsigned int addrSize, unsigned int dummySize, unsigned int dataSize)
Definition at line 92 of file device_access.xc.
References g_portHolder.
Referenced by fl_connectToDevice(), fl_int_getBusyStatus(), fl_int_getFullStatus(), fl_int_programPageAsync(), fl_setProtection(), fl_setSectorProtection(), and fl_setWritability().
int fl_int_programPage (const fl_DeviceSpec & flashAccess, unsigned int pageAddress, const unsigned char data[])
Definition at line 245 of file device_access.xc.
References fl_int_programPageAsync(), and fl_int_waitWhileWriting().
int fl_int_programPageAsync (const fl_DeviceSpec & flashAccess, unsigned int pageAddress, const unsigned char data[])
Definition at line 188 of file device_access.xc.
References fl_getPageSize(), fl_int_issueShortCommand(), fl_int_waitWhileWriting(), and g_portHolder.
Referenced by fl_int_programPage().
int fl_int_readBytes (const fl_DeviceSpec & flashAccess, unsigned pageAddress, unsigned char data[], unsigned int numBytes)
Definition at line 264 of file device_access.xc.
References g_portHolder.
int fl_int_spiInit (int div)
Definition at line 51 of file device_access.xc.
References g_portHolder.
Referenced by fl_connectToDevice().
int fl_int_spiMasterInit (void)
Definition at line 46 of file device_access.xc.
Referenced by fl_connectToDevice().
void fl_int_waitWhileWriting (const fl_DeviceSpec & flashAccess)
Definition at line 176 of file device_access.xc.
References fl_int_getBusyStatus().
Referenced by fl_int_programPage(), and fl_int_programPageAsync().
Variable Documentation
int g_fl_int_doWaitForCompletion
fl_PortHolderStruct g_portHolder
Definition at line 62 of file flashlib.c.
Referenced by fl_connectToDevice(), fl_int_issueShortCommand(), fl_int_programPageAsync(), fl_int_readBytes(), and fl_int_spiInit().