sc_somanet-base: app_linux_fwupdate/src/ethercatprint.h File Reference
ethercatprint.h File Reference
Headerfile for ethercatprint.c.
Functions
char * ec_sdoerror2string (uint16 sdoerrorcode)
char * ec_ALstatuscode2string (uint16 ALstatuscode)
char * ec_soeerror2string (uint16 errorcode)
char * ec_elist2string (void)
Detailed Description
Headerfile for ethercatprint.c.
Definition in file ethercatprint.h.
Function Documentation
char* ec_ALstatuscode2string (uint16 ALstatuscode)
Look up text string that belongs to AL status code.
Parameters
[in] ALstatuscode = AL status code as defined in EtherCAT protocol
Returns
readable string
Definition at line 234 of file ethercatprint.c.
References ec_ALstatuscodelist_t::ALstatuscodedescription.
Referenced by firmware_update(), and slaveinfo().
char* ec_elist2string (void)
Look up error in ec_errorlist and convert to text string.
Returns
readable string
Definition at line 271 of file ethercatprint.c.
References ec_errort::AbortCode, EC_ERR_TYPE_EMERGENCY, EC_ERR_TYPE_PACKET_ERROR, EC_ERR_TYPE_SDO_ERROR, EC_ERR_TYPE_SDOINFO_ERROR, EC_ERR_TYPE_SOE_ERROR, ec_poperror(), ec_sdoerror2string(), ec_soeerror2string(), ec_errort::ErrorCode, estring, ec_errort::Etype, ec_errort::Index, ec_errort::Slave, ec_errort::SubIdx, and ec_errort::Time.
Referenced by SDO2string(), and slaveinfo().
char* ec_sdoerror2string (uint16 sdoerrorcode)
char* ec_soeerror2string (uint16 errorcode)
Look up text string that belongs to SoE error code.
Parameters
[in] errorcode = AL status code as defined in EtherCAT protocol
Returns
readable string
Definition at line 253 of file ethercatprint.c.
References ec_soeerrorlist_t::errordescription.
Referenced by ec_elist2string().