sc_somanet-base: app_linux_fwupdate/src/ethercatmain.h File Reference
ethercatmain.h File Reference
Headerfile for ethercatmain.c.
Data Structures
struct PACKED
struct PACKED
struct PACKED
struct ec_slavet
struct ec_groupt
struct ec_eepromFMMUt
struct ec_eepromSMt
struct ec_eepromPDOt
struct PACKED
struct PACKED
Macros
#define PACKED __attribute__((__packed__))
#define EC_MAXELIST 64
#define EC_MAXNAME 36
#define EC_MAXSLAVE 200
#define EC_MAXGROUP 8
#define EC_MAXIOSEGMENTS 64
#define EC_MAXMBX 0x3ff
#define EC_MAXEEPDO 0x200
#define EC_MAXSM 8
#define EC_MAXFMMU 4
#define ECT_MBXPROT_AOE 0x0001
#define ECT_MBXPROT_EOE 0x0002
#define ECT_MBXPROT_COE 0x0004
#define ECT_MBXPROT_FOE 0x0008
#define ECT_MBXPROT_SOE 0x0010
#define ECT_MBXPROT_VOE 0x0020
#define ECT_COEDET_SDO 0x01
#define ECT_COEDET_SDOINFO 0x02
#define ECT_COEDET_PDOASSIGN 0x04
#define ECT_COEDET_PDOCONFIG 0x08
#define ECT_COEDET_UPLOAD 0x10
#define ECT_COEDET_SDOCA 0x20
#define EC_SMENABLEMASK 0xfffeffff
Typedefs
typedef struct PACKED ec_fmmut
typedef struct PACKED ec_smt
typedef struct PACKED ec_state_status
typedef uint8 ec_mbxbuft [EC_MAXMBX+1]
typedef struct PACKED ec_mbxheadert
typedef struct PACKED ec_alstatust
Functions
void ec_pusherror (const ec_errort *Ec)
boolean ec_poperror (ec_errort *Ec)
boolean ec_iserror (void)
void ec_packeterror (uint16 Slave, uint16 Index, uint8 SubIdx, uint16 ErrorCode)
int ec_init (const char *ifname)
int ec_init_redundant (const char *ifname, const char *if2name)
void ec_close (void)
uint8 ec_siigetbyte (uint16 slave, uint16 address)
int16 ec_siifind (uint16 slave, uint16 cat)
void ec_siistring (char *str, uint16 slave, uint16 Sn)
uint16 ec_siiFMMU (uint16 slave, ec_eepromFMMUt *FMMU)
uint16 ec_siiSM (uint16 slave, ec_eepromSMt *SM)
uint16 ec_siiSMnext (uint16 slave, ec_eepromSMt *SM, uint16 n)
int ec_siiPDO (uint16 slave, ec_eepromPDOt *PDO, uint8 t)
int ec_readstate (void)
int ec_writestate (uint16 slave)
uint16 ec_statecheck (uint16 slave, uint16 reqstate, int timeout)
uint8 ec_nextmbxcnt (uint8 cnt)
void ec_clearmbx (ec_mbxbuft *Mbx)
int ec_mbxempty (uint16 slave, int timeout)
int ec_mbxsend (uint16 slave, ec_mbxbuft *mbx, int timeout)
int ec_mbxreceive (uint16 slave, ec_mbxbuft *mbx, int timeout)
void ec_esidump (uint16 slave, uint8 *esibuf, uint8 test)
uint32 ec_readeeprom (uint16 slave, uint16 eeproma, int timeout)
int ec_writeeeprom (uint16 slave, uint16 eeproma, uint16 data, int timeout)
int ec_eeprom2master (uint16 slave)
int ec_eeprom2pdi (uint16 slave)
uint64 ec_readeepromAP (uint16 aiadr, uint16 eeproma, int timeout)
int ec_writeeepromAP (uint16 aiadr, uint16 eeproma, uint16 data, int timeout)
uint64 ec_readeepromFP (uint16 configadr, uint16 eeproma, int timeout)
int ec_writeeepromFP (uint16 configadr, uint16 eeproma, uint16 data, int timeout)
void ec_readeeprom1 (uint16 slave, uint16 eeproma)
uint32 ec_readeeprom2 (uint16 slave, int timeout)
int ec_send_processdata_group (uint8 group)
int ec_receive_processdata_group (uint8 group, int timeout)
int ec_send_processdata (void)
int ec_receive_processdata (int timeout)
Variables
ec_slavet ec_slave [EC_MAXSLAVE]
int ec_slavecount
ec_groupt ec_group [EC_MAXGROUP]
boolean EcatError
uint16 ec_DCtO
int64 ec_DCtime
Detailed Description
Headerfile for ethercatmain.c.
Definition in file ethercatmain.h.
Macro Definition Documentation
#define EC_MAXEEPDO 0x200
max. eeprom PDO entries
Definition at line 66 of file ethercatmain.h.
Referenced by ec_siiPDO().
#define EC_MAXELIST 64
max. etries in EtherCAT error list
Definition at line 54 of file ethercatmain.h.
Referenced by ec_poperror(), and ec_pusherror().
#define EC_MAXFMMU 4
max. FMMU used
Definition at line 70 of file ethercatmain.h.
#define EC_MAXGROUP 8
max. number of groups
Definition at line 60 of file ethercatmain.h.
Referenced by ec_config_init(), and ec_config_map_group().
#define EC_MAXIOSEGMENTS 64
max. number of IO segments per group
Definition at line 62 of file ethercatmain.h.
Referenced by ec_config_map_group().
#define EC_MAXMBX 0x3ff
max. mailbox size
Definition at line 64 of file ethercatmain.h.
Referenced by ec_clearmbx().
#define EC_MAXNAME 36
max. length of readable name in slavelist and Object Description List
Definition at line 56 of file ethercatmain.h.
Referenced by ec_readODdescription().
#define EC_MAXSLAVE 200
max. number of slaves in array
Definition at line 58 of file ethercatmain.h.
#define EC_MAXSM 8
max. SM used
Definition at line 68 of file ethercatmain.h.
Referenced by ec_config_init(), ec_config_map_group(), ec_readPDOmap(), ec_readPDOmapCA(), ec_reconfig_slave(), ec_siiPDO(), and slaveinfo().
#define EC_SMENABLEMASK 0xfffeffff
Definition at line 116 of file ethercatmain.h.
Referenced by ec_config_map_group(), ec_readPDOmap(), and ec_readPDOmapCA().
#define ECT_COEDET_PDOASSIGN 0x04
Definition at line 111 of file ethercatmain.h.
#define ECT_COEDET_PDOCONFIG 0x08
Definition at line 112 of file ethercatmain.h.
#define ECT_COEDET_SDO 0x01
Definition at line 109 of file ethercatmain.h.
#define ECT_COEDET_SDOCA 0x20
Definition at line 114 of file ethercatmain.h.
Referenced by ec_config_map_group().
#define ECT_COEDET_SDOINFO 0x02
Definition at line 110 of file ethercatmain.h.
#define ECT_COEDET_UPLOAD 0x10
Definition at line 113 of file ethercatmain.h.
#define ECT_MBXPROT_AOE 0x0001
Definition at line 102 of file ethercatmain.h.
#define ECT_MBXPROT_COE 0x0004
Definition at line 104 of file ethercatmain.h.
Referenced by ec_config_map_group().
#define ECT_MBXPROT_EOE 0x0002
Definition at line 103 of file ethercatmain.h.
#define ECT_MBXPROT_FOE 0x0008
Definition at line 105 of file ethercatmain.h.
#define ECT_MBXPROT_SOE 0x0010
Definition at line 106 of file ethercatmain.h.
Referenced by ec_config_map_group().
#define ECT_MBXPROT_VOE 0x0020
Definition at line 107 of file ethercatmain.h.
#define PACKED __attribute__((__packed__))
Definition at line 50 of file ethercatmain.h.
Typedef Documentation
typedef struct PACKED ec_alstatust
ALstatus and ALstatus code
typedef struct PACKED ec_fmmut
record for FMMU
typedef uint8 ec_mbxbuft[EC_MAXMBX+1]
mailbox buffer array
Definition at line 321 of file ethercatmain.h.
typedef struct PACKED ec_mbxheadert
standard ethercat mailbox header
typedef struct PACKED ec_smt
record for sync manager
typedef struct PACKED ec_state_status
Function Documentation
void ec_clearmbx (ec_mbxbuft * Mbx)
Clear mailbox buffer.
Parameters
[out] Mbx = Mailbox buffer to clear
Definition at line 684 of file ethercatmain.c.
References EC_MAXMBX.
Referenced by ec_FOEread(), ec_FOEwrite(), ec_readODdescription(), ec_readODlist(), ec_RxPDO(), ec_SDOread(), ec_SDOwrite(), ec_SoEread(), ec_SoEwrite(), ec_TxPDO(), and send_mbx().
void ec_close (void)
Close lib.
Definition at line 259 of file ethercatmain.c.
References ec_closenic().
Referenced by firmware_update(), and slaveinfo().
int ec_eeprom2master (uint16 slave)
Set eeprom control to master. Only if set to PDI.
Parameters
[in] slave = Slave number
Returns
>0 if OK
Definition at line 905 of file ethercatmain.c.
References ec_slavet::configadr, EC_DEFAULTRETRIES, ec_FPWR(), EC_TIMEOUTRET, ECT_REG_EEPCFG, and ec_slavet::eep_pdi.
Referenced by ec_esidump(), ec_readeeprom(), ec_readeeprom1(), ec_recover_slave(), ec_siigetbyte(), and ec_writeeeprom().
int ec_eeprom2pdi (uint16 slave)
Set eeprom control to PDI. Only if set to master.
Parameters
[in] slave = Slave number
Returns
>0 if OK
Definition at line 937 of file ethercatmain.c.
References ec_slavet::configadr, EC_DEFAULTRETRIES, ec_FPWR(), EC_TIMEOUTRET, ECT_REG_EEPCFG, and ec_slavet::eep_pdi.
Referenced by ec_config_map_group(), ec_esidump(), ec_reconfig_slave(), ec_siifind(), ec_siiFMMU(), ec_siiPDO(), ec_siiSM(), ec_siiSMnext(), and ec_siistring().
void ec_esidump (uint16 slave, uint8 * esibuf, uint8 test)
Dump complete EEPROM data from slave in buffer.
Parameters
[in] slave = Slave number
[out] esibuf = EEPROM data buffer, make sure it is big enough.
Definition at line 840 of file ethercatmain.c.
References ec_slavet::configadr, ec_eeprom2master(), ec_eeprom2pdi(), EC_MAXEEPBUF, ec_readeepromFP(), EC_TIMEOUTEEP, ECT_SII_START, and ec_slavet::eep_pdi.
int ec_init (const char * ifname)
Initialise lib in single NIC mode
Parameters
[in] ifname = Dev name, f.e. "eth0"
Returns
>0 if OK
Definition at line 230 of file ethercatmain.c.
References ec_setupnic(), and FALSE.
Referenced by firmware_update(), and slaveinfo().
int ec_init_redundant (const char * ifname, const char * if2name)
Initialise lib in redundant NIC mode
Parameters
[in] ifname = Primary Dev name, f.e. "eth0"
[in] if2name = Secondary Dev name, f.e. "eth1"
Returns
>0 if OK
Definition at line 240 of file ethercatmain.c.
References EC_CMD_BRD, EC_HEADERSIZE, ec_setupdatagram(), ec_setupnic(), ec_txbuf2, ec_txbuflength2, EC_WKCSIZE, ETH_HEADERSIZE, FALSE, PACKED::sa1, secMAC, and TRUE.
boolean ec_iserror (void)
Check if error list has entries.
Returns
TRUE if error list contains entries.
Definition at line 173 of file ethercatmain.c.
References ec_eringt::head, and ec_eringt::tail.
int ec_mbxempty (uint16 slave, int timeout)
Check if IN mailbox of slave is empty.
Parameters
[in] slave = Slave number
[in] timeout = Timeout in us
Returns
>0 is success
Definition at line 694 of file ethercatmain.c.
References ec_slavet::configadr, ec_FPRD(), EC_LOCALDELAY, EC_TIMEOUTRET, ECT_REG_SM0STAT, and etohs.
Referenced by ec_mbxsend(), and ec_SoEwrite().
int ec_mbxreceive (uint16 slave, ec_mbxbuft * mbx, int timeout)
Read OUT mailbox from slave. Supports Mailbox Link Layer with repeat requests.
Parameters
[in] slave = Slave number
[out] mbx = Mailbox data
[in] timeout = Timeout in us
Returns
Work counter (>0 is success)
Definition at line 754 of file ethercatmain.c.
References ec_emcyt::bData, ec_emcyt::CANOpen, ec_slavet::configadr, ec_FPRD(), ec_FPWR(), EC_LOCALDELAY, EC_TIMEOUTRET, ECT_REG_SM1CONTR, ECT_REG_SM1STAT, ec_emcyt::ErrorCode, ec_emcyt::ErrorReg, etohs, HI_BYTE, htoes, ec_slavet::mbx_rl, ec_slavet::mbx_ro, PACKED::mbxtype, ec_emcyt::w1, and ec_emcyt::w2.
Referenced by ec_FOEread(), ec_FOEwrite(), ec_readODdescription(), ec_readODlist(), ec_RxPDO(), ec_SDOread(), ec_SDOwrite(), ec_SoEread(), ec_SoEwrite(), and ec_TxPDO().
int ec_mbxsend (uint16 slave, ec_mbxbuft * mbx, int timeout)
Write IN mailbox to slave.
Parameters
[in] slave = Slave number
[out] mbx = Mailbox data
[in] timeout = Timeout in us
Returns
Work counter (>0 is success)
Definition at line 724 of file ethercatmain.c.
References ec_slavet::configadr, ec_FPWR(), ec_mbxempty(), EC_TIMEOUTRET, ec_slavet::mbx_l, and ec_slavet::mbx_wo.
Referenced by ec_FOEread(), ec_FOEwrite(), ec_readODdescription(), ec_readODlist(), ec_RxPDO(), ec_SDOread(), ec_SDOwrite(), ec_SoEread(), ec_SoEwrite(), ec_TxPDO(), and send_mbx().
uint8 ec_nextmbxcnt (uint8 cnt)
Get index of next mailbox counter value. Used for Mailbox Link Layer.
Parameters
[in] cnt = Mailbox counter value [0..7]
Returns
next mailbox counter value
Definition at line 673 of file ethercatmain.c.
Referenced by ec_FOEread(), ec_FOEwrite(), ec_readODdescription(), ec_readODlist(), ec_RxPDO(), ec_SDOread(), ec_SDOwrite(), ec_SoEread(), ec_SoEwrite(), and ec_TxPDO().
void ec_packeterror (uint16 Slave, uint16 Index, uint8 SubIdx, uint16 ErrorCode)
Report packet error
Parameters
[in] Slave = Slave number
[in] Index = Index that generated error
[in] SubIdx = Subindex that generated error
[in] ErrorCode = Error code
Definition at line 185 of file ethercatmain.c.
References EC_ERR_TYPE_PACKET_ERROR, ec_pusherror(), EcatError, ec_errort::ErrorCode, ec_errort::Etype, ec_errort::Index, ec_errort::Slave, ec_errort::SubIdx, ec_errort::Time, and TRUE.
Referenced by ec_readODdescription(), ec_readODlist(), ec_SDOread(), ec_SDOwrite(), ec_SoEread(), ec_SoEwrite(), and ec_TxPDO().
boolean ec_poperror (ec_errort * Ec)
Pops an error from the list.
Parameters
[out] Ec = Struct describing the error.
Returns
TRUE if an error was popped.
Definition at line 153 of file ethercatmain.c.
References EC_MAXELIST, EcatError, ec_eringt::Error, FALSE, ec_eringt::head, ec_errort::Signal, and ec_eringt::tail.
Referenced by ec_elist2string().
void ec_pusherror (const ec_errort * Ec)
Pushes an error on the error list.
Parameters
[in] Ec Struct describing the error.
Definition at line 134 of file ethercatmain.c.
References EC_MAXELIST, EcatError, ec_eringt::Error, ec_eringt::head, ec_errort::Signal, ec_eringt::tail, and TRUE.
Referenced by ec_packeterror(), ec_SDOerror(), and ec_SoEerror().
uint32 ec_readeeprom (uint16 slave, uint16 eeproma, int timeout)
Read EEPROM from slave bypassing cache.
Parameters
[in] slave = Slave number
[in] eeproma = (WORD) Address in the EEPROM
[in] timeout = Timeout in us.
Returns
EEPROM data 32bit
Definition at line 875 of file ethercatmain.c.
References ec_slavet::configadr, ec_eeprom2master(), and ec_readeepromFP().
Referenced by ec_config_init(), and ec_recover_slave().
void ec_readeeprom1 (uint16 slave, uint16 eeproma)
Read EEPROM from slave bypassing cache. Parallel read step 1, make request to slave.
Parameters
[in] slave = Slave number
[in] eeproma = (WORD) Address in the EEPROM
Definition at line 1283 of file ethercatmain.c.
References PACKED::addr, PACKED::comm, ec_slavet::configadr, PACKED::d2, EC_DEFAULTRETRIES, EC_ECMD_NOP, EC_ECMD_READ, ec_eeprom2master(), ec_eeprom_waitnotbusyFP(), EC_ESTAT_EMASK, ec_FPWR(), EC_TIMEOUTEEP, EC_TIMEOUTRET, ECT_REG_EEPCTL, and htoes.
Referenced by ec_config_init().
uint32 ec_readeeprom2 (uint16 slave, int timeout)
Read EEPROM from slave bypassing cache. Parallel read step 2, actual read from slave.
Parameters
[in] slave = Slave number
[in] timeout = Timeout in us.
Returns
EEPROM data 32bit
Definition at line 1313 of file ethercatmain.c.
References ec_slavet::configadr, EC_DEFAULTRETRIES, ec_eeprom_waitnotbusyFP(), ec_FPRD(), EC_TIMEOUTRET, and ECT_REG_EEPDAT.
Referenced by ec_config_init().
uint64 ec_readeepromAP (uint16 aiadr, uint16 eeproma, int timeout)
Read EEPROM from slave bypassing cache. APRD method.
Parameters
[in] aiadr = auto increment address of slave
[in] eeproma = (WORD) Address in the EEPROM
[in] timeout = Timeout in us.
Returns
EEPROM data 64bit or 32bit
Definition at line 985 of file ethercatmain.c.
References PACKED::addr, PACKED::comm, PACKED::d2, ec_APRD(), ec_APWR(), EC_DEFAULTRETRIES, EC_ECMD_NOP, EC_ECMD_READ, ec_eeprom_waitnotbusyAP(), EC_ESTAT_EMASK, EC_ESTAT_NACK, EC_ESTAT_R64, EC_LOCALDELAY, EC_TIMEOUTRET, ECT_REG_EEPCTL, ECT_REG_EEPDAT, and htoes.
Referenced by eeprom_read().
uint64 ec_readeepromFP (uint16 configadr, uint16 eeproma, int timeout)
Read EEPROM from slave bypassing cache. FPRD method.
Parameters
[in] configadr = configured address of slave
[in] eeproma = (WORD) Address in the EEPROM
[in] timeout = Timeout in us.
Returns
EEPROM data 64bit or 32bit
Definition at line 1146 of file ethercatmain.c.
References PACKED::addr, PACKED::comm, PACKED::d2, EC_DEFAULTRETRIES, EC_ECMD_NOP, EC_ECMD_READ, ec_eeprom_waitnotbusyFP(), EC_ESTAT_EMASK, EC_ESTAT_NACK, EC_ESTAT_R64, ec_FPRD(), ec_FPWR(), EC_LOCALDELAY, EC_TIMEOUTRET, ECT_REG_EEPCTL, ECT_REG_EEPDAT, and htoes.
Referenced by ec_esidump(), ec_readeeprom(), and ec_siigetbyte().
int ec_readstate (void)
Read all slave states in ec_slave.
Returns
lowest state found
Definition at line 576 of file ethercatmain.c.
References PACKED::alstatus, ec_slavet::ALstatuscode, PACKED::alstatuscode, ec_slavet::configadr, ec_FPRD(), ec_slavecount, EC_TIMEOUTRET, ECT_REG_ALSTAT, etohs, and ec_slavet::state.
Referenced by firmware_update(), and slaveinfo().
int ec_receive_processdata (int timeout)
Definition at line 1555 of file ethercatmain.c.
References ec_receive_processdata_group().
Referenced by firmware_update(), and slave_operation().
int ec_receive_processdata_group (uint8 group, int timeout)
Receive processdata from slaves. Second part from ec_send_processdata(). Received datagrams are recombined with the processdata with help from the stack. If a datagram contains input processdata it copies it to the processdata structure.
Parameters
[in] timeout = Timeout in us.
Returns
Work counter.
Definition at line 1507 of file ethercatmain.c.
References ec_idxstackT::data, EC_BUF_EMPTY, EC_CMD_LRD, EC_CMD_LRW, EC_CMDOFFSET, ec_DCtime, ec_DCtO, EC_HEADERSIZE, EC_NOFRAME, ec_rxbuf, ec_setbufstat(), ec_waitinframe(), EC_WKCSIZE, etohll, etohs, FALSE, ec_idxstackT::idx, ec_idxstackT::length, and TRUE.
Referenced by ec_receive_processdata().
int ec_send_processdata (void)
Definition at line 1550 of file ethercatmain.c.
References ec_send_processdata_group().
Referenced by firmware_update(), and slave_operation().
int ec_send_processdata_group (uint8 group)
Transmit processdata to slaves. Uses LRW, or LRD/LWR if LRW is not allowed (blockLRW). Both the input and output processdata are transmitted. The outputs with the actual data, the inputs have a placeholder. The inputs are gathered with the receive processdata function. In contrast to the base LRW function this function is non-blocking. If the processdata does not fit in one datagram, multiple are used. In order to recombine the slave response, a stack is used.
Returns
>0 if processdata is transmitted.
Definition at line 1378 of file ethercatmain.c.
References ec_adddatagram(), EC_CMD_FRMW, EC_CMD_LRD, EC_CMD_LRW, EC_CMD_LWR, ec_DCtime, ec_DCtO, ec_getindex(), ec_outframe_red(), ec_setupdatagram(), ec_txbuf, ECT_REG_DCSYSTIME, FALSE, HI_WORD, ec_groupt::Ibytes, ec_groupt::inputs, ec_groupt::Ioffset, ec_groupt::IOsegment, ec_groupt::Isegment, LO_WORD, ec_groupt::logstartaddr, ec_groupt::Obytes, ec_groupt::outputs, ec_idxstackT::pulled, ec_idxstackT::pushed, and TRUE.
Referenced by ec_send_processdata().
int16 ec_siifind (uint16 slave, uint16 cat)
Find SII section header in slave EEPROM.
Parameters
[in] slave = slave number
[in] cat = section category
Returns
byte address of section at section length entry, if not available then 0
Definition at line 339 of file ethercatmain.c.
References ec_eeprom2pdi(), ec_siigetbyte(), ECT_SII_START, and ec_slavet::eep_pdi.
Referenced by ec_config_init(), ec_siiFMMU(), ec_siiPDO(), ec_siiSM(), ec_siistring(), and slaveinfo().
uint16 ec_siiFMMU (uint16 slave, ec_eepromFMMUt * FMMU)
Get FMMU data from SII FMMU section in slave EEPROM.
Parameters
[in] slave = slave number
[out] FMMU = FMMU struct from SII, max. 4 FMMU's
Returns
number of FMMU's defined in section
Definition at line 415 of file ethercatmain.c.
References ec_eeprom2pdi(), ec_siifind(), ec_siigetbyte(), ECT_SII_FMMU, ec_slavet::eep_pdi, ec_eepromFMMUt::FMMU0, ec_eepromFMMUt::FMMU1, ec_eepromFMMUt::FMMU2, ec_eepromFMMUt::FMMU3, ec_eepromFMMUt::nFMMU, and ec_eepromFMMUt::Startpos.
Referenced by ec_config_init().
uint8 ec_siigetbyte (uint16 slave, uint16 address)
Read one byte from slave EEPROM via cache. If the cache location is empty then a read request is made to the slave. Depending on the slave capabillities the request is 4 or 8 bytes.
Parameters
[in] slave = slave number
[in] address = eeprom address in bytes (slave uses words)
Returns
requested byte, if not available then 0xff
Definition at line 271 of file ethercatmain.c.
References ec_slavet::configadr, ec_eeprom2master(), EC_MAXEEPBITMAP, EC_MAXEEPBUF, ec_readeepromFP(), EC_TIMEOUTEEP, put_unaligned32, and put_unaligned64.
Referenced by ec_config_init(), ec_siifind(), ec_siiFMMU(), ec_siiPDO(), ec_siiSM(), ec_siiSMnext(), ec_siistring(), and slaveinfo().
int ec_siiPDO (uint16 slave, ec_eepromPDOt * PDO, uint8 t)
Get PDO data from SII PDO section in slave EEPROM.
Parameters
[in] slave = slave number
[out] PDO = PDO struct from SII
[in] t = 0=RXPDO 1=TXPDO
Returns
mapping size in bits of PDO
Definition at line 512 of file ethercatmain.c.
References ec_eepromPDOt::BitSize, ec_eeprom2pdi(), EC_MAXEEPDO, EC_MAXSM, ec_siifind(), ec_siigetbyte(), ECT_SII_PDO, ec_slavet::eep_pdi, ec_eepromPDOt::Index, ec_eepromPDOt::Length, ec_eepromPDOt::nPDO, ec_eepromPDOt::SMbitsize, ec_eepromPDOt::Startpos, and ec_eepromPDOt::SyncM.
Referenced by ec_config_map_group().
uint16 ec_siiSM (uint16 slave, ec_eepromSMt * SM)
Get SM data from SII SM section in slave EEPROM.
Parameters
[in] slave = slave number
[out] SM = first SM struct from SII
Returns
number of SM's defined in section
Definition at line 450 of file ethercatmain.c.
References ec_eepromSMt::Activate, ec_eepromSMt::Creg, ec_eeprom2pdi(), ec_siifind(), ec_siigetbyte(), ECT_SII_SM, ec_slavet::eep_pdi, ec_eepromSMt::nSM, ec_eepromSMt::PDIctrl, ec_eepromSMt::PhStart, ec_eepromSMt::Plength, ec_eepromSMt::Sreg, and ec_eepromSMt::Startpos.
Referenced by ec_config_init().
uint16 ec_siiSMnext (uint16 slave, ec_eepromSMt * SM, uint16 n)
Get next SM data from SII SM section in slave EEPROM.
Parameters
[in] slave = slave number
[out] SM = first SM struct from SII
[in] n = SM number
Returns
>0 if OK
Definition at line 483 of file ethercatmain.c.
References ec_eepromSMt::Activate, ec_eepromSMt::Creg, ec_eeprom2pdi(), ec_siigetbyte(), ec_slavet::eep_pdi, ec_eepromSMt::PDIctrl, ec_eepromSMt::PhStart, ec_eepromSMt::Plength, ec_eepromSMt::Sreg, and ec_eepromSMt::Startpos.
Referenced by ec_config_init().
void ec_siistring (char * str, uint16 slave, uint16 Sn)
Get string from SII string section in slave EEPROM.
Parameters
[out] str = requested string, 0x00 if not found
[in] slave = slave number
[in] Sn = string number
Definition at line 374 of file ethercatmain.c.
References ec_eeprom2pdi(), ec_siifind(), ec_siigetbyte(), ECT_SII_STRING, and ec_slavet::eep_pdi.
Referenced by ec_config_init().
uint16 ec_statecheck (uint16 slave, uint16 reqstate, int timeout)
Check actual slave state. This is a blocking function.
Parameters
[in] slave = Slave number, 0 = all slaves
[in] reqstate = Requested state
[in] timeout = Timout value in us
Returns
Requested state, or found state after timeout.
Definition at line 630 of file ethercatmain.c.
References ec_slavet::ALstatuscode, ec_slavet::configadr, ec_BRD(), ec_FPRD(), ec_slavecount, EC_TIMEOUTRET, ECT_REG_ALSTAT, etohs, and ec_slavet::state.
Referenced by ec_config_init(), ec_config_map_group(), ec_reconfig_slave(), firmware_update(), and slaveinfo().
int ec_writeeeprom (uint16 slave, uint16 eeproma, uint16 data, int timeout)
Write EEPROM to slave bypassing cache.
Parameters
[in] slave = Slave number
[in] eeproma = (WORD) Address in the EEPROM
[in] data = 16bit data
[in] timeout = Timeout in us.
Returns
>0 if OK
Definition at line 891 of file ethercatmain.c.
References ec_slavet::configadr, ec_eeprom2master(), and ec_writeeepromFP().
int ec_writeeepromAP (uint16 aiadr, uint16 eeproma, uint16 data, int timeout)
Write EEPROM to slave bypassing cache. APWR method.
Parameters
[in] aiadr = configured address of slave
[in] eeproma = (WORD) Address in the EEPROM
[in] data = 16bit data
[in] timeout = Timeout in us.
Returns
>0 if OK
Definition at line 1062 of file ethercatmain.c.
References PACKED::addr, PACKED::comm, PACKED::d2, ec_APWR(), EC_DEFAULTRETRIES, EC_ECMD_NOP, EC_ECMD_WRITE, ec_eeprom_waitnotbusyAP(), EC_ESTAT_EMASK, EC_ESTAT_NACK, EC_LOCALDELAY, EC_TIMEOUTRET, ECT_REG_EEPCTL, ECT_REG_EEPDAT, and htoes.
int ec_writeeepromFP (uint16 configadr, uint16 eeproma, uint16 data, int timeout)
Write EEPROM to slave bypassing cache. FPWR method.
Parameters
[in] configadr = configured address of slave
[in] eeproma = (WORD) Address in the EEPROM
[in] data = 16bit data
[in] timeout = Timeout in us.
Returns
>0 if OK
Definition at line 1223 of file ethercatmain.c.
References PACKED::addr, PACKED::comm, PACKED::d2, EC_DEFAULTRETRIES, EC_ECMD_NOP, EC_ECMD_WRITE, ec_eeprom_waitnotbusyFP(), EC_ESTAT_EMASK, EC_ESTAT_NACK, ec_FPWR(), EC_LOCALDELAY, EC_TIMEOUTRET, ECT_REG_EEPCTL, ECT_REG_EEPDAT, and htoes.
Referenced by ec_writeeeprom().
int ec_writestate (uint16 slave)
Write slave state, if slave = 0 then write to all slaves. The function does not check if the actual state is changed.
Parameters
[in] slave = Slave number, 0 = master
Returns
0
Definition at line 606 of file ethercatmain.c.
References ec_slavet::configadr, ec_BWR(), ec_FPWRw(), EC_TIMEOUTRET, ECT_REG_ALCTL, and htoes.
Referenced by firmware_update().
Variable Documentation
int64 ec_DCtime
Definition at line 128 of file ethercatmain.c.
Referenced by ec_receive_processdata_group(), and ec_send_processdata_group().
uint16 ec_DCtO
Definition at line 126 of file ethercatmain.c.
Referenced by ec_receive_processdata_group(), and ec_send_processdata_group().
ec_groupt ec_group[EC_MAXGROUP]
slave group structure
Definition at line 112 of file ethercatmain.c.
Referenced by ec_config_init(), ec_config_map_group(), ec_configdc(), slave_operation(), and slaveinfo().
ec_slavet ec_slave[EC_MAXSLAVE]
main slave data structure array
Main slave data array. Each slave found on the network gets its own record. ec_slave[0] is reserved for the master. Structure gets filled in by the configuration function ec_config().
Definition at line 108 of file ethercatmain.c.
Referenced by ec_config_init(), ec_config_map_group(), ec_configdc(), ec_dcsync0(), ec_dcsync01(), ec_FOEread(), ec_FOEwrite(), ec_parentport(), ec_porttime(), ec_prevport(), ec_readODdescription(), ec_readODlist(), ec_readPDOmap(), ec_readPDOmapCA(), ec_reconfig_slave(), ec_recover_slave(), ec_RxPDO(), ec_SDOread(), ec_SDOwrite(), ec_SoEread(), ec_SoEwrite(), ec_TxPDO(), firmware_update(), slave_operation(), and slaveinfo().
int ec_slavecount
number of slaves found by configuration function
number of slaves found on the network
Definition at line 110 of file ethercatmain.c.
Referenced by ec_config_init(), ec_config_map_group(), ec_configdc(), ec_readstate(), ec_statecheck(), eeprom_read(), firmware_update(), slave_operation(), and slaveinfo().
boolean EcatError
Global variable TRUE if error available in error stack
Definition at line 124 of file ethercatmain.c.
Referenced by ec_packeterror(), ec_poperror(), ec_pusherror(), ec_SDOerror(), ec_SoEerror(), SDO2string(), and slaveinfo().