sc_somanet-base: app_linux_fwupdate/src/ethercatcoe.c File Reference
ethercatcoe.c File Reference
CAN over EtherCAT (CoE) module.
#include <stdio.h>
#include <string.h>
#include <sys/time.h>
#include <unistd.h>
#include "ethercattype.h"
#include "nicdrv.h"
#include "ethercatbase.h"
#include "ethercatmain.h"
#include "ethercatcoe.h"
Data Structures
struct PACKED
struct PACKED
struct PACKED
struct PACKED
struct PACKED
Typedefs
typedef struct PACKED ec_SDOt
typedef struct PACKED ec_SDOservicet
typedef struct PACKED ec_SMcommtypet
typedef struct PACKED ec_PDOassignt
typedef struct PACKED ec_PDOdesct
Functions
void ec_SDOerror (uint16 Slave, uint16 Index, uint8 SubIdx, int32 AbortCode)
int ec_SDOread (uint16 slave, uint16 index, uint8 subindex, boolean CA, int *psize, void *p, int timeout)
int ec_SDOwrite (uint16 Slave, uint16 Index, uint8 SubIndex, boolean CA, int psize, void *p, int Timeout)
int ec_RxPDO (uint16 Slave, uint16 RxPDOnumber, int psize, void *p)
int ec_TxPDO (uint16 slave, uint16 TxPDOnumber, int *psize, void *p, int timeout)
int ec_readPDOassign (uint16 Slave, uint16 PDOassign)
int ec_readPDOassignCA (uint16 Slave, uint16 PDOassign)
int ec_readPDOmap (uint16 Slave, int *Osize, int *Isize)
int ec_readPDOmapCA (uint16 Slave, int *Osize, int *Isize)
int ec_readODlist (uint16 Slave, ec_ODlistt *pODlist)
int ec_readODdescription (uint16 Item, ec_ODlistt *pODlist)
int ec_readOE (uint16 Item, ec_ODlistt *pODlist, ec_OElistt *pOElist)
Detailed Description
CAN over EtherCAT (CoE) module.
SDO read / write and SDO service functions
Definition in file ethercatcoe.c.
Typedef Documentation
typedef struct PACKED ec_PDOassignt
SDO assign structure for CA
typedef struct PACKED ec_PDOdesct
SDO description structure for CA
typedef struct PACKED ec_SDOservicet
SDO service structure
typedef struct PACKED ec_SDOt
SDO structure, not to be confused with EcSDOserviceT
typedef struct PACKED ec_SMcommtypet
SyncManager Communication Type structure for CA
Function Documentation
int ec_readODdescription (uint16 Item, ec_ODlistt * pODlist)
CoE read Object Description. Adds textual description to object indexes.
Parameters
[in] Item = Item number in ODlist.
[in,out] pODlist = referencing Object Description list.
Returns
Workcounter of slave response.
Definition at line 1016 of file ethercatcoe.c.
References PACKED::address, PACKED::bdata, PACKED::CANOpen, ec_ODlistt::DataType, ec_clearmbx(), EC_MAXNAME, ec_mbxreceive(), ec_mbxsend(), ec_nextmbxcnt(), ec_packeterror(), ec_slave, EC_TIMEOUTRXM, EC_TIMEOUTTXM, ECT_COES_SDOINFO, ECT_GET_OD_REQ, ECT_GET_OD_RES, ECT_MBXT_COE, ECT_SDOINFO_ERROR, etohl, etohs, PACKED::Fragments, htoes, ec_ODlistt::Index, PACKED::ldata, PACKED::length, ec_ODlistt::MaxSub, ec_slavet::mbx_cnt, PACKED::MbxHeader, PACKED::mbxtype, ec_ODlistt::Name, ec_ODlistt::ObjectCode, PACKED::Opcode, PACKED::priority, PACKED::Reserved, ec_ODlistt::Slave, and PACKED::wdata.
Referenced by slaveinfo().
int ec_readODlist (uint16 Slave, ec_ODlistt * pODlist)
CoE read Object Description List.
Parameters
[in] Slave = Slave number.
[out] pODlist = resulting Object Description list.
Returns
Workcounter of slave response.
Definition at line 910 of file ethercatcoe.c.
References PACKED::address, PACKED::CANOpen, ec_clearmbx(), EC_MAXODLIST, ec_mbxreceive(), ec_mbxsend(), ec_nextmbxcnt(), ec_packeterror(), ec_slave, EC_TIMEOUTRXM, EC_TIMEOUTTXM, ECT_COES_SDOINFO, ECT_GET_ODLIST_REQ, ECT_GET_ODLIST_RES, ECT_MBXT_COE, ECT_SDOINFO_ERROR, ec_ODlistt::Entries, etohl, etohs, FALSE, PACKED::Fragments, htoes, ec_ODlistt::Index, PACKED::ldata, PACKED::length, ec_slavet::mbx_cnt, PACKED::MbxHeader, PACKED::mbxtype, PACKED::Opcode, PACKED::priority, PACKED::Reserved, ec_ODlistt::Slave, TRUE, and PACKED::wdata.
Referenced by slaveinfo().
int ec_readOE (uint16 Item, ec_ODlistt * pODlist, ec_OElistt * pOElist)
CoE read SDO service object entry.
Parameters
[in] Item = Item in ODlist.
[in] pODlist = Object description list for reference.
[out] pOElist = resulting object entry structure.
Returns
Workcounter of slave response.
Definition at line 1174 of file ethercatcoe.c.
References ec_OElistt::Entries, and ec_ODlistt::MaxSub.
Referenced by slaveinfo().
int ec_readPDOassign (uint16 Slave, uint16 PDOassign)
Read PDO assign structure
Definition at line 640 of file ethercatcoe.c.
References ec_SDOread(), EC_TIMEOUTRXM, etohl, etohs, FALSE, htoes, and LO_BYTE.
Referenced by ec_readPDOmap().
int ec_readPDOassignCA (uint16 Slave, uint16 PDOassign)
Read PDO assign structure in Complete Access mode
Definition at line 697 of file ethercatcoe.c.
References ec_SDOread(), EC_TIMEOUTRXM, etohl, etohs, PACKED::index, LO_BYTE, PACKED::n, PACKED::PDO, and TRUE.
Referenced by ec_readPDOmapCA().
int ec_readPDOmap (uint16 Slave, int * Osize, int * Isize)
CoE read PDO mapping.
CANopen has standard indexes defined for PDO mapping. This function tries to read them and collect a full input and output mapping size of designated slave.
Principal structure in slave:
1C00:00 is number of SM defined
1C00:01 SM0 type -> 1C10
1C00:02 SM1 type -> 1C11
1C00:03 SM2 type -> 1C12
1C00:04 SM4 type -> 1C13
Type 0 = unused, 1 = mailbox in, 2 = mailbox out, 3 = outputs (RxPDO), 4 = inputs (TxPDO).
1C12:00 is number of PDO's defined for SM2
1C12:01 PDO assign SDO #1 -> f.e. 1A00
1C12:02 PDO assign SDO #2 -> f.e. 1A04\
1A00:00 is number of object defined for this PDO
1A00:01 object mapping #1, f.e. 60100710 (SDO 6010 SI 07 bitlength 0x10)
Parameters
[in] Slave = Slave number
[out] Osize = Size in bits of output mapping (rxPDO) found
[out] Isize = Size in bits of input mapping (txPDO) found
Returns
>0 if mapping succesful.
Definition at line 762 of file ethercatcoe.c.
References EC_MAXSM, ec_readPDOassign(), ec_SDOread(), ec_slave, EC_SMENABLEMASK, EC_TIMEOUTRXM, ECT_SDO_PDOASSIGN, ECT_SDO_SMCOMMTYPE, etohl, FALSE, htoel, htoes, ec_slavet::SM, PACKED::SMflags, PACKED::SMlength, and ec_slavet::SMtype.
Referenced by ec_config_map_group().
int ec_readPDOmapCA (uint16 Slave, int * Osize, int * Isize)
CoE read PDO mapping in Complete Access mode (CA).
CANopen has standard indexes defined for PDO mapping. This function tries to read them and collect a full input and output mapping size of designated slave. Slave has to support CA, otherwise use ec_readPDOmap().
Parameters
[in] Slave = Slave number
[out] Osize = Size in bits of output mapping (rxPDO) found
[out] Isize = Size in bits of input mapping (txPDO) found
Returns
>0 if mapping succesful.
Definition at line 840 of file ethercatcoe.c.
References EC_MAXSM, ec_readPDOassignCA(), ec_SDOread(), ec_slave, EC_SMENABLEMASK, EC_TIMEOUTRXM, ECT_SDO_PDOASSIGN, ECT_SDO_SMCOMMTYPE, etohl, htoel, htoes, PACKED::n, ec_slavet::SM, PACKED::SMflags, PACKED::SMlength, PACKED::SMtype, ec_slavet::SMtype, and TRUE.
Referenced by ec_config_map_group().
int ec_RxPDO (uint16 Slave, uint16 RxPDOnumber, int psize, void * p)
CoE RxPDO write, blocking.
A RxPDO download request is issued.
Parameters
[in] Slave = Slave number
[in] RxPDOnumber = Related RxPDO number
[in] psize = Size in bytes of PDO buffer.
[out] p = Pointer to PDO buffer
Returns
Workcounter from last slave response
Definition at line 529 of file ethercatcoe.c.
References PACKED::address, PACKED::CANOpen, PACKED::Command, ec_clearmbx(), ec_mbxreceive(), ec_mbxsend(), ec_nextmbxcnt(), ec_slave, EC_TIMEOUTTXM, ECT_COES_RXPDO, ECT_MBXT_COE, htoes, PACKED::length, ec_slavet::mbx_cnt, ec_slavet::mbx_l, PACKED::MbxHeader, PACKED::mbxtype, and PACKED::priority.
void ec_SDOerror (uint16 Slave, uint16 Index, uint8 SubIdx, int32 AbortCode)
Report SDO error.
Parameters
[in] Slave = Slave number
[in] Index = Index that generated error
[in] SubIdx = Subindex that generated error
[in] AbortCode = Abortcode, see EtherCAT documentation for list
Definition at line 128 of file ethercatcoe.c.
References ec_errort::AbortCode, EC_ERR_TYPE_SDO_ERROR, ec_pusherror(), EcatError, ec_errort::Etype, ec_errort::Index, ec_errort::Slave, ec_errort::SubIdx, ec_errort::Time, and TRUE.
Referenced by ec_SDOread(), ec_SDOwrite(), and ec_TxPDO().
int ec_SDOread (uint16 slave, uint16 index, uint8 subindex, boolean CA, int * psize, void * p, int timeout)
CoE SDO read, blocking. Single subindex or Complete Access.
Only a "normal" upload request is issued. If the requested parameter is <= 4bytes then a "expedited" response is returned, otherwise a "normal" response. If a "normal" response is larger than the mailbox size then the response is segmented. The function will combine all segments and copy them to the parameter buffer.
Parameters
[in] slave = Slave number
[in] index = Index to read
[in] subindex = Subindex to read, must be 0 or 1 if CA is used.
[in] CA = FALSE = single subindex. TRUE = Complete Access, all subindexes read.
[in,out] psize = Size in bytes of parameter buffer, returns bytes read from SDO.
[out] p = Pointer to parameter buffer
[in] timeout = Timeout in us, standard is EC_TIMEOUTRXM
Returns
Workcounter from last slave response
Definition at line 179 of file ethercatcoe.c.
References PACKED::address, PACKED::CANOpen, PACKED::Command, ec_clearmbx(), ec_mbxreceive(), ec_mbxsend(), ec_nextmbxcnt(), ec_packeterror(), ec_SDOerror(), ec_slave, EC_TIMEOUTTXM, ECT_COES_SDOREQ, ECT_COES_SDORES, ECT_MBXT_COE, ECT_SDO_ABORT, ECT_SDO_SEG_UP_REQ, ECT_SDO_UP_REQ, ECT_SDO_UP_REQ_CA, etohl, etohs, FALSE, htoes, PACKED::Index, PACKED::ldata, PACKED::length, ec_slavet::mbx_cnt, PACKED::MbxHeader, PACKED::mbxtype, PACKED::priority, PACKED::SubIndex, and TRUE.
Referenced by ec_readPDOassign(), ec_readPDOassignCA(), ec_readPDOmap(), ec_readPDOmapCA(), and SDO2string().
int ec_SDOwrite (uint16 Slave, uint16 Index, uint8 SubIndex, boolean CA, int psize, void * p, int Timeout)
CoE SDO write, blocking. Single subindex or Complete Access.
Only a "normal" download request is issued. If the paramater is larger than the mailbox size then the download is segmented. The function will split the parameter data in segments and send them to the slave one by one.
Parameters
[in] Slave = Slave number
[in] Index = Index to write
[in] SubIndex = Subindex to write, must be 0 or 1 if CA is used.
[in] CA = FALSE = single subindex. TRUE = Complete Access, all subindexes written.
[in] psize = Size in bytes of parameter buffer.
[out] p = Pointer to parameter buffer
[in] Timeout = Timeout in us, standard is EC_TIMEOUTRXM
Returns
Workcounter from last slave response
Definition at line 377 of file ethercatcoe.c.
References PACKED::address, PACKED::CANOpen, PACKED::Command, ec_clearmbx(), ec_mbxreceive(), ec_mbxsend(), ec_nextmbxcnt(), ec_packeterror(), ec_SDOerror(), ec_slave, EC_TIMEOUTTXM, ECT_COES_SDOREQ, ECT_COES_SDORES, ECT_MBXT_COE, ECT_SDO_ABORT, ECT_SDO_DOWN_INIT, ECT_SDO_DOWN_INIT_CA, etohl, etohs, FALSE, htoel, htoes, PACKED::Index, PACKED::ldata, PACKED::length, ec_slavet::mbx_cnt, ec_slavet::mbx_l, PACKED::MbxHeader, PACKED::mbxtype, PACKED::priority, PACKED::SubIndex, and TRUE.
int ec_TxPDO (uint16 slave, uint16 TxPDOnumber, int * psize, void * p, int timeout)
CoE TxPDO read remote request, blocking.
A RxPDO download request is issued.
Parameters
[in] slave = Slave number
[in] TxPDOnumber = Related TxPDO number
[in,out] psize = Size in bytes of PDO buffer, returns bytes read from PDO.
[out] p = Pointer to PDO buffer
[in] timeout = Timeout in us, standard is EC_TIMEOUTRXM
Returns
Workcounter from last slave response
Definition at line 573 of file ethercatcoe.c.
References PACKED::address, PACKED::CANOpen, PACKED::Command, ec_clearmbx(), ec_mbxreceive(), ec_mbxsend(), ec_nextmbxcnt(), ec_packeterror(), ec_SDOerror(), ec_slave, EC_TIMEOUTTXM, ECT_COES_TXPDO, ECT_COES_TXPDO_RR, ECT_MBXT_COE, ECT_SDO_ABORT, etohl, etohs, htoes, PACKED::ldata, PACKED::length, ec_slavet::mbx_cnt, PACKED::MbxHeader, PACKED::mbxtype, and PACKED::priority.