sc_somanet-base: module_fwupdate/flash_write.c File Reference
flash_write.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <flashlib.h>
#include <platform.h>
#include <flash.h>
Functions
void flash_erase ()
int flash_connect ()
void flash_setup (int factory)
void flash_buffer (char content[], int imageSize, unsigned address)
int flash_buf_end (void)
Detailed Description
Copyright (c) 2014, Synapticon GmbH All rights reserved. Author: Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file flash_write.c.
Function Documentation
int flash_buf_end (void)
Definition at line 106 of file flash_write.c.
References fl_endWriteImage().
Referenced by check_file_access().
void flash_buffer (char content[], int imageSize, unsigned address)
Definition at line 85 of file flash_write.c.
References fl_writePage().
Referenced by check_file_access().
int flash_connect ()
Definition at line 70 of file flash_somanet.xc.
References fl_connect().
Referenced by flash_setup().
void flash_erase ()
Definition at line 47 of file flash_write.c.
References fl_eraseAll().
Referenced by flash_setup().
void flash_setup (int factory)
Definition at line 55 of file flash_write.c.
References fl_setProtection(), flash_connect(), and flash_erase().
Referenced by check_file_access().