sc_somanet-base: app_linux_fwupdate/src/fw_update.c File Reference
fw_update.c File Reference
Firmware Update for Synapticon SOMANET (modified from Example code for Simple Open EtherCAT master)
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <sys/time.h>
#include <unistd.h>
#include <stdint.h>
#include "ethercattype.h"
#include "nicdrv.h"
#include "ethercatbase.h"
#include "ethercatmain.h"
#include "ethercatcoe.h"
#include "ethercatfoe.h"
#include "ethercatconfig.h"
#include "ethercatprint.h"
Macros
#define MBX_VOE_TYPE 0xF
#define READDUMMYTEST 0
#define MAX_MBXDATALENGTH 0x200 /* this size is copied from ethercatcoe.c */
#define MODE_NONE 0
#define MODE_SERIAL 1
#define MODE_SEQUENTIAL 2
#define MODE_ALL 3
#define MODE_SCAN 4
#define MAXBUF 32768
Functions
struct __attribute__ ((__packed__))
int send_mbx (uint16_t slave, uint8_t *data, size_t length)
int start_file (uint16 slave)
int end_file (uint16 slave)
int slave_testfoe (uint16 slave, char *filename)
int slave_operation (int oloop, int iloop, boolean needlf)
int eeprom_read (int slave, int start, int length)
void firmware_update (char *ifname, char *filename, int *ser_no, int mode, int seq_id)
int main (int argc, char *argv[])
Variables
ec_VOEmbx_t
char IOmap [4096]
uint8 ebuf [MAXBUF]
Detailed Description
Firmware Update for Synapticon SOMANET (modified from Example code for Simple Open EtherCAT master)
Usage: fw_update eth0 OPTION id filepath OPTION: -s specify serial number for the ethercat slave -seq specify slave number in EtherCAT order 1..n -all use all slaves connected to the system -scan scan the slave/slaves connected and display their serial number
specify the ID number after options for these options -s & -seq followed by /path/to/your/file
SOEM is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
SOEM is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
As a special exception, if other files instantiate templates or use macros or inline functions from this file, or you compile this file and link it with other works to produce a work based on this file, this file does not by itself cause the resulting work to be covered by the GNU General Public License. However the source code for this file must still be made available in accordance with section (3) of the GNU General Public License.
This exception does not invalidate any other reasons why a work based on this file might be covered by the GNU General Public License.
The EtherCAT Technology, the trade name and logo “EtherCAT” are the intellectual property of, and protected by Beckhoff Automation GmbH. You can use SOEM for the sole purpose of creating, using and/or selling or otherwise distributing an EtherCAT network master provided that an EtherCAT Master License is obtained from Beckhoff Automation GmbH.
In case you did not receive a copy of the EtherCAT Master License along with SOEM write to Beckhoff Automation GmbH, Eiserstraße 5, D-33415 Verl, Germany (www.beckhoff.com).
Copyright 2014, Synapticon GmbH. All rights reserved (c) Authors : Arthur Ketels 2010 - 2011 (original simpletest) (c) Authors : Frank Jeschke jesch.nosp@m.ke@f.nosp@m.jes.d.nosp@m.e & Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Definition in file fw_update.c.
Macro Definition Documentation
#define MAX_MBXDATALENGTH 0x200 /* this size is copied from ethercatcoe.c */
Definition at line 68 of file fw_update.c.
Referenced by __attribute__(), and send_mbx().
#define MAXBUF 32768
Definition at line 288 of file fw_update.c.
Referenced by eeprom_read().
#define MBX_VOE_TYPE 0xF
Definition at line 66 of file fw_update.c.
#define MODE_ALL 3
Definition at line 72 of file fw_update.c.
Referenced by main().
#define MODE_NONE 0
Definition at line 69 of file fw_update.c.
Referenced by main().
#define MODE_SCAN 4
Definition at line 73 of file fw_update.c.
Referenced by main().
#define MODE_SEQUENTIAL 2
Definition at line 71 of file fw_update.c.
Referenced by main().
#define MODE_SERIAL 1
Definition at line 70 of file fw_update.c.
Referenced by main().
#define READDUMMYTEST 0
Definition at line 67 of file fw_update.c.
Function Documentation
struct __attribute__ ((__packed__))
Definition at line 75 of file fw_update.c.
References MAX_MBXDATALENGTH.
int eeprom_read (int slave, int start, int length)
Definition at line 290 of file fw_update.c.
References ebuf, ec_APRD(), ec_APWR(), EC_ESTAT_R64, ec_readeepromAP(), ec_slavecount, EC_TIMEOUTEEP, EC_TIMEOUTRET, ECT_REG_EEPCFG, ECT_REG_EEPSTAT, etohs, and MAXBUF.
Referenced by firmware_update().
int end_file (uint16 slave)
Definition at line 112 of file fw_update.c.
References ec_FOEwrite().
Referenced by slave_testfoe().
void firmware_update (char * ifname, char * filename, int * ser_no, int mode, int seq_id)
Definition at line 344 of file fw_update.c.
References ebuf, ec_ALstatuscode2string(), ec_close(), ec_config_init(), ec_config_map(), ec_init(), ec_readstate(), ec_receive_processdata(), ec_send_processdata(), ec_slave, ec_slavecount, EC_STATE_INIT, EC_STATE_OPERATIONAL, EC_STATE_SAFE_OP, ec_statecheck(), EC_TIMEOUTRET, EC_TIMEOUTSTATE, ec_writestate(), eeprom_read(), FALSE, ec_slavet::Ibytes, IOmap, ec_slavet::Obytes, slave_testfoe(), and ec_slavet::state.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 501 of file fw_update.c.
References firmware_update(), MODE_ALL, MODE_NONE, MODE_SCAN, MODE_SEQUENTIAL, and MODE_SERIAL.
int send_mbx (uint16_t slave, uint8_t * data, size_t length)
Definition at line 82 of file fw_update.c.
References ec_clearmbx(), ec_mbxsend(), EC_TIMEOUTTXM, ec_VOEmbx_t, ECT_MBXT_VOE, htoes, and MAX_MBXDATALENGTH.
int slave_operation (int oloop, int iloop, boolean needlf)
Definition at line 213 of file fw_update.c.
References ec_group, ec_receive_processdata(), ec_send_processdata(), ec_slave, ec_slavecount, EC_STATE_OPERATIONAL, EC_TIMEOUTRET, ec_slavet::outputs, and TRUE.
int slave_testfoe (uint16 slave, char * filename)
Definition at line 121 of file fw_update.c.
References ec_FOEwrite(), end_file(), and start_file().
Referenced by firmware_update().
int start_file (uint16 slave)
Definition at line 103 of file fw_update.c.
References ec_FOEwrite().
Referenced by slave_testfoe().
Variable Documentation
uint8 ebuf[MAXBUF]
Definition at line 289 of file fw_update.c.
Referenced by eeprom_read(), and firmware_update().
ec_VOEmbx_t
Definition at line 78 of file fw_update.c.
Referenced by send_mbx().
char IOmap[4096]
Definition at line 80 of file fw_update.c.
Referenced by firmware_update().