sc_somanet-base: app_linux_fwupdate/src/ethercatdc.h File Reference
ethercatdc.h File Reference
Headerfile for ethercatdc.c.
Functions
boolean ec_configdc ()
void ec_dcsync0 (uint16 slave, boolean act, uint32 CyclTime, uint32 CyclShift)
void ec_dcsync01 (uint16 slave, boolean act, uint32 CyclTime0, uint32 CyclTime1, uint32 CyclShift)
Variables
uint16 DCrefSlave
uint16 DClistN
Detailed Description
Headerfile for ethercatdc.c.
Definition in file ethercatdc.h.
Function Documentation
boolean ec_configdc (void)
Set DC's of all slaves to sync with the first, measure propagation delays.
return DCfound
Locate DC slaves, measure propagation delays.
return boolean if slaves are found with DC
Definition at line 266 of file ethercatdc.c.
References ec_slavet::activeports, ec_slavet::configadr, ec_slavet::consumedports, ec_slavet::DCnext, ec_groupt::DCnext, ec_slavet::DCprevious, ec_slavet::DCrtA, ec_slavet::DCrtB, ec_slavet::DCrtC, ec_slavet::DCrtD, ec_BWR(), ec_FPRD(), ec_FPWR(), ec_group, ec_parentport(), ec_porttime(), ec_prevport(), ec_slave, ec_slavecount, EC_TIMEOUTRET, ECT_REG_DCSOF, ECT_REG_DCSYSDELAY, ECT_REG_DCSYSOFFSET, ECT_REG_DCTIME0, ECT_REG_DCTIME1, ECT_REG_DCTIME2, ECT_REG_DCTIME3, ec_slavet::entryport, etohl, etohll, FALSE, ec_slavet::hasdc, ec_groupt::hasdc, htoel, htoell, ec_slavet::parent, ec_slavet::parentport, ec_slavet::pdelay, PORTM0, PORTM1, PORTM2, PORTM3, and TRUE.
Referenced by slaveinfo().
void ec_dcsync0 (uint16 slave, boolean act, uint32 CyclTime, uint32 CyclShift)
Set DC of slave to fire sync0 at CyclTime interval with CyclShift offset.
Parameters
[in] slave Slave number.
[in] act TRUE = active, FALSE = deactivated
[in] CyclTime Cycltime in ns.
[in] CyclShift CyclShift in ns.
Definition at line 68 of file ethercatdc.c.
References ec_slavet::configadr, ec_FPRD(), ec_FPWR(), ec_slave, EC_TIMEOUTRET, ECT_REG_DCCUC, ECT_REG_DCCYCLE0, ECT_REG_DCSTART0, ECT_REG_DCSYNCACT, ECT_REG_DCSYSTIME, etohll, htoel, htoell, and SyncDelay.
void ec_dcsync01 (uint16 slave, boolean act, uint32 CyclTime0, uint32 CyclTime1, uint32 CyclShift)
Set DC of slave to fire sync0 and sync1 at CyclTime interval with CyclShift offset.
Parameters
[in] slave Slave number.
[in] act TRUE = active, FALSE = deactivated
[in] CyclTime0 Cycltime SYNC0 in ns.
[in] CyclTime1 Cycltime SYNC1 in ns. This time is a delta time in relation to the SYNC0 fire. If CylcTime1 = 0 then SYNC1 fires a the same time as SYNC0.
[in] CyclShift CyclShift in ns.
Definition at line 120 of file ethercatdc.c.
References ec_slavet::configadr, ec_FPRD(), ec_FPWR(), ec_slave, EC_TIMEOUTRET, ECT_REG_DCCUC, ECT_REG_DCCYCLE0, ECT_REG_DCCYCLE1, ECT_REG_DCSTART0, ECT_REG_DCSYNCACT, ECT_REG_DCSYSTIME, etohll, htoel, htoell, and SyncDelay.
Variable Documentation
uint16 DClistN
uint16 DCrefSlave