sc_somanet-base: app_linux_fwupdate/src/ethercatsoe.c File Reference
ethercatsoe.c File Reference
Servo over EtherCAT (SoE) Module.
#include <stdio.h>
#include <string.h>
#include <sys/time.h>
#include <unistd.h>
#include "ethercattype.h"
#include "nicdrv.h"
#include "ethercatbase.h"
#include "ethercatmain.h"
#include "ethercatsoe.h"
Data Structures
struct PACKED
Typedefs
typedef struct PACKED ec_SoEt
Functions
void ec_SoEerror (uint16 Slave, uint16 idn, uint16 Error)
int ec_SoEread (uint16 slave, uint8 driveNo, uint8 elementflags, uint16 idn, int *psize, void *p, int timeout)
int ec_SoEwrite (uint16 slave, uint8 driveNo, uint8 elementflags, uint16 idn, int psize, void *p, int timeout)
int ec_readIDNmap (uint16 slave, int *Osize, int *Isize)
Detailed Description
Servo over EtherCAT (SoE) Module.
Definition in file ethercatsoe.c.
Typedef Documentation
typedef struct PACKED ec_SoEt
SoE (Servo over EtherCAT) mailbox structure
Function Documentation
int ec_readIDNmap (uint16 slave, int * Osize, int * Isize)
SoE read AT and MTD mapping.
SoE has standard indexes defined for mapping. This function tries to read them and collect a full input and output mapping size of designated slave.
Parameters
[in] Slave = Slave number
[out] Osize = Size in bits of output mapping (MTD) found
[out] Isize = Size in bits of input mapping (AT) found
Returns
>0 if mapping succesful.
Definition at line 343 of file ethercatsoe.c.
References PACKED::currentlength, EC_IDN_ATCONFIG, EC_IDN_MDTCONFIG, EC_SOE_ATTRIBUTE_B, EC_SOE_MAXMAPPING, EC_SOE_VALUE_B, ec_SoEread(), EC_TIMEOUTRXM, etohs, PACKED::idn, PACKED::length, and PACKED::list.
Referenced by ec_config_map_group().
void ec_SoEerror (uint16 Slave, uint16 idn, uint16 Error)
Report SoE error.
Parameters
[in] Slave = Slave number
[in] idn = IDN that generated error
[in] Error = Error code, see EtherCAT documentation for list
Definition at line 82 of file ethercatsoe.c.
References EC_ERR_TYPE_SOE_ERROR, ec_pusherror(), EcatError, ec_errort::ErrorCode, ec_errort::Etype, ec_errort::Index, ec_errort::Slave, ec_errort::SubIdx, ec_errort::Time, and TRUE.
Referenced by ec_SoEread(), and ec_SoEwrite().
int ec_SoEread (uint16 slave, uint8 driveNo, uint8 elementflags, uint16 idn, int * psize, void * p, int timeout)
SoE read, blocking.
The IDN object of the selected slave and DriveNo is read. If a response is larger than the mailbox size then the response is segmented. The function will combine all segments and copy them to the parameter buffer.
Parameters
[in] slave = Slave number
[in] driveNo = Drive number in slave
[in] elementflags = Flags to select what properties of IDN are to be transfered.
[in] idn = IDN.
[in,out] psize = Size in bytes of parameter buffer, returns bytes read from SoE.
[out] p = Pointer to parameter buffer
[in] timeout = Timeout in us, standard is EC_TIMEOUTRXM
Returns
Workcounter from last slave response
Definition at line 111 of file ethercatsoe.c.
References PACKED::address, PACKED::driveNo, ec_clearmbx(), ec_mbxreceive(), ec_mbxsend(), ec_nextmbxcnt(), ec_packeterror(), ec_slave, ec_SoEerror(), EC_TIMEOUTTXM, ECT_MBXT_SOE, ECT_SOE_READREQ, ECT_SOE_READRES, PACKED::elementflags, PACKED::error, etohs, FALSE, htoes, PACKED::idn, PACKED::incomplete, PACKED::length, ec_slavet::mbx_cnt, PACKED::MbxHeader, PACKED::mbxtype, PACKED::opCode, PACKED::priority, and TRUE.
Referenced by ec_readIDNmap().
int ec_SoEwrite (uint16 slave, uint8 driveNo, uint8 elementflags, uint16 idn, int psize, void * p, int timeout)
SoE write, blocking.
The IDN object of the selected slave and DriveNo is written. If a response is larger than the mailbox size then the response is segmented.
Parameters
[in] slave = Slave number
[in] driveNo = Drive number in slave
[in] elementflags = Flags to select what properties of IDN are to be transfered.
[in] idn = IDN.
[in] psize = Size in bytes of parameter buffer.
[out] p = Pointer to parameter buffer
[in] timeout = Timeout in us, standard is EC_TIMEOUTRXM
Returns
Workcounter from last slave response
Definition at line 232 of file ethercatsoe.c.
References PACKED::address, PACKED::driveNo, ec_clearmbx(), ec_mbxempty(), ec_mbxreceive(), ec_mbxsend(), ec_nextmbxcnt(), ec_packeterror(), ec_slave, ec_SoEerror(), EC_TIMEOUTTXM, ECT_MBXT_SOE, ECT_SOE_READRES, ECT_SOE_WRITEREQ, ECT_SOE_WRITERES, PACKED::elementflags, PACKED::error, etohs, FALSE, PACKED::fragmentsleft, htoes, PACKED::idn, PACKED::incomplete, PACKED::length, ec_slavet::mbx_cnt, ec_slavet::mbx_l, PACKED::MbxHeader, PACKED::mbxtype, PACKED::opCode, PACKED::priority, and TRUE.