sc_somanet-base: app_linux_fwupdate/src/ethercatconfig.c File Reference
ethercatconfig.c File Reference
Configuration module for EtherCAT master.
#include <stdio.h>
#include <string.h>
#include <sys/time.h>
#include <unistd.h>
#include "ethercattype.h"
#include "nicdrv.h"
#include "ethercatbase.h"
#include "ethercatmain.h"
#include "ethercatcoe.h"
#include "ethercatsoe.h"
#include "ethercatconfig.h"
#include "ethercatconfiglist.h"
Data Structures
struct ec_configlist_t
Macros
#define EC_PRINT(...) do {} while (0)
#define EC_DEFAULTMBXSM0 0x00010026
#define EC_DEFAULTMBXSM1 0x00010022
#define EC_DEFAULTDOSM0 0x00010044
Functions
int ec_findconfig (uint32 man, uint32 id)
int ec_config_init (uint8 usetable)
int ec_config_map_group (void *pIOmap, uint8 group)
int ec_config_map (void *pIOmap)
int ec_config (uint8 usetable, void *pIOmap)
int ec_recover_slave (uint16 slave)
int ec_reconfig_slave (uint16 slave)
Detailed Description
Configuration module for EtherCAT master.
After successful initialisation with ec_init() or ec_init_redundant() the slaves can be auto configured with this module.
Definition in file ethercatconfig.c.
Macro Definition Documentation
#define EC_DEFAULTDOSM0 0x00010044
standard SM0 flags configuration for digital output slaves
Definition at line 106 of file ethercatconfig.c.
Referenced by ec_config_init().
#define EC_DEFAULTMBXSM0 0x00010026
standard SM0 flags configuration for mailbox slaves
Definition at line 102 of file ethercatconfig.c.
Referenced by ec_config_init().
#define EC_DEFAULTMBXSM1 0x00010022
standard SM1 flags configuration for mailbox slaves
Definition at line 104 of file ethercatconfig.c.
Referenced by ec_config_init().
#define EC_PRINT (...) do {} while (0)
Definition at line 67 of file ethercatconfig.c.
Referenced by ec_config_init(), and ec_config_map_group().
Function Documentation
int ec_config (uint8 usetable, void * pIOmap)
Enumerate / map and init all slaves.
Parameters
[in] usetable = TRUE when using configtable to init slaves, FALSE otherwise
[out] pIOmap = pointer to IOmap
Returns
Workcounter of slave discover datagram = number of slaves found
Definition at line 907 of file ethercatconfig.c.
References ec_config_init(), and ec_config_map().
Referenced by slaveinfo().
int ec_config_init (uint8 usetable)
Enumerate and init all slaves.
Parameters
[in] usetable = TRUE when using configtable to init slaves, FALSE otherwise
Returns
Workcounter of slave discover datagram = number of slaves found
Definition at line 139 of file ethercatconfig.c.
References ec_eepromSMt::Activate, ec_slavet::activeports, ec_slavet::blockLRW, ec_slavet::CoEdetails, ec_slavet::configadr, ec_slavet::configindex, ec_eepromSMt::Creg, ec_configlist_t::Dtype, ec_slavet::Dtype, ec_slavet::Ebuscurrent, ec_APRDw(), ec_APWRw(), ec_BRD(), ec_BWR(), ec_configlist, EC_DEFAULTDOSM0, EC_DEFAULTMBXSM0, EC_DEFAULTMBXSM1, EC_ESTAT_R64, ec_findconfig(), ec_FPRD(), ec_FPRDw(), ec_FPWR(), ec_FPWRw(), ec_group, EC_MAXGROUP, EC_MAXSM, EC_NODEOFFSET, EC_PRINT, ec_readeeprom(), ec_readeeprom1(), ec_readeeprom2(), ec_siifind(), ec_siiFMMU(), ec_siigetbyte(), ec_siiSM(), ec_siiSMnext(), ec_siistring(), ec_slave, ec_slavecount, EC_STATE_ACK, EC_STATE_INIT, EC_STATE_PRE_OP, ec_statecheck(), EC_TIMEOUTEEP, EC_TIMEOUTRET, EC_TIMEOUTSAFE, EC_TIMEOUTSTATE, ECT_REG_ALCTL, ECT_REG_ALIAS, ECT_REG_DCSPEEDCNT, ECT_REG_DCSYSTIME, ECT_REG_DCTIMEFILT, ECT_REG_DLALIAS, ECT_REG_DLCTL, ECT_REG_DLPORT, ECT_REG_DLSTAT, ECT_REG_EEPCFG, ECT_REG_EEPSTAT, ECT_REG_ESCSUP, ECT_REG_FMMU0, ECT_REG_IRQMASK, ECT_REG_PDICTL, ECT_REG_PORTDES, ECT_REG_RXERR, ECT_REG_SM0, ECT_REG_SM1, ECT_REG_STADR, ECT_REG_TYPE, ECT_SII_GENERAL, ECT_SII_ID, ECT_SII_MANUF, ECT_SII_MBXPROTO, ECT_SII_REV, ECT_SII_RXMBXADR, ECT_SII_STRING, ECT_SII_TXMBXADR, ec_slavet::eep_8byte, ec_slavet::eep_id, ec_slavet::eep_man, ec_slavet::eep_rev, ec_slavet::EoEdetails, etohl, etohs, FALSE, ec_configlist_t::FM0ac, ec_configlist_t::FM1ac, ec_slavet::FMMU, ec_eepromFMMUt::FMMU0, ec_slavet::FMMU0func, ec_eepromFMMUt::FMMU1, ec_slavet::FMMU1func, ec_eepromFMMUt::FMMU2, ec_slavet::FMMU2func, ec_eepromFMMUt::FMMU3, ec_slavet::FMMU3func, PACKED::FMMUactive, PACKED::FMMUtype, ec_slavet::FoEdetails, ec_slavet::hasdc, HI_WORD, htoel, htoes, ec_configlist_t::Ibits, ec_slavet::Ibits, ec_slavet::Itype, LO_BYTE, LO_WORD, ec_groupt::logstartaddr, ec_slavet::mbx_l, ec_slavet::mbx_proto, ec_slavet::mbx_rl, ec_slavet::mbx_ro, ec_slavet::mbx_wo, ec_configlist_t::Obits, ec_slavet::Obits, ec_slavet::parent, ec_eepromSMt::PhStart, ec_eepromSMt::Plength, ec_slavet::ptype, ec_slavet::SM, PACKED::SMflags, PACKED::SMlength, ec_slavet::SMtype, ec_slavet::SoEdetails, PACKED::StartAddr, ec_slavet::topology, and TRUE.
Referenced by ec_config(), and firmware_update().
int ec_config_map (void * pIOmap)
Map all PDOs from slaves to IOmap.
Parameters
[out] pIOmap = pointer to IOmap
Returns
IOmap size
Definition at line 896 of file ethercatconfig.c.
References ec_config_map_group().
Referenced by ec_config(), and firmware_update().
int ec_config_map_group (void * pIOmap, uint8 group)
Map all PDOs in one group of slaves to IOmap.
Parameters
[out] pIOmap = pointer to IOmap
[in] group = group to map, 0 = all groups
Returns
IOmap size
Definition at line 474 of file ethercatconfig.c.
References ec_groupt::blockLRW, ec_slavet::configadr, ec_slavet::Ebuscurrent, ec_groupt::Ebuscurrent, ec_eeprom2pdi(), EC_FIRSTDCDATAGRAM, ec_FPWR(), ec_FPWRw(), ec_group, EC_MAXGROUP, EC_MAXIOSEGMENTS, EC_MAXLRWDATA, EC_MAXSM, EC_PRINT, ec_readIDNmap(), ec_readPDOmap(), ec_readPDOmapCA(), ec_siiPDO(), ec_slave, ec_slavecount, EC_SMENABLEMASK, EC_STATE_PRE_OP, EC_STATE_SAFE_OP, ec_statecheck(), EC_TIMEOUTRET, EC_TIMEOUTSTATE, ECT_COEDET_SDOCA, ECT_MBXPROT_COE, ECT_MBXPROT_SOE, ECT_REG_ALCTL, ECT_REG_FMMU0, ECT_REG_SM0, ECT_REG_SM1, etohl, etohs, ec_groupt::expectedWKC, ec_slavet::FMMU, PACKED::FMMUactive, PACKED::FMMUtype, ec_slavet::FMMUunused, htoel, htoes, ec_slavet::Ibits, ec_slavet::Ibytes, ec_groupt::Ibytes, ec_slavet::inputs, ec_groupt::inputs, ec_groupt::Ioffset, ec_groupt::IOsegment, ec_groupt::Isegment, ec_slavet::Istartbit, PACKED::LogEndbit, PACKED::LogLength, PACKED::LogStart, ec_groupt::logstartaddr, PACKED::LogStartbit, ec_groupt::nsegments, ec_slavet::Obits, ec_slavet::Obytes, ec_groupt::Obytes, ec_slavet::Ostartbit, ec_slavet::outputs, ec_groupt::outputs, PACKED::PhysStart, PACKED::PhysStartBit, ec_slavet::SM, ec_eepromPDOt::SMbitsize, PACKED::SMflags, PACKED::SMlength, ec_slavet::SMtype, and PACKED::StartAddr.
Referenced by ec_config_map().
int ec_findconfig (uint32 man, uint32 id)
Find slave in standard configuration list ec_configlist[]
Parameters
[in] man = manufacturer
[in] id = ID
Returns
index in ec_configlist[] when found, otherwise 0
Definition at line 119 of file ethercatconfig.c.
References EC_CONFIGEND, and ec_configlist.
Referenced by ec_config_init().
int ec_reconfig_slave (uint16 slave)
Reconfigure slave.
Parameters
[in] slave = slave to reconfigure
Returns
Slave state
Definition at line 962 of file ethercatconfig.c.
References ec_slavet::configadr, ec_eeprom2pdi(), ec_FPWR(), ec_FPWRw(), EC_MAXSM, ec_slave, EC_STATE_INIT, EC_STATE_PRE_OP, EC_STATE_SAFE_OP, ec_statecheck(), EC_TIMEOUTRET, EC_TIMEOUTSTATE, ECT_REG_ALCTL, ECT_REG_FMMU0, ECT_REG_SM0, ec_slavet::FMMUunused, and htoes.
int ec_recover_slave (uint16 slave)
Recover slave.
Parameters
[in] slave = slave to recover
Returns
>0 if successful
Definition at line 921 of file ethercatconfig.c.
References ec_slavet::configadr, ec_APWRw(), ec_eeprom2master(), ec_FPRDw(), ec_FPWRw(), ec_readeeprom(), ec_slave, EC_TEMPNODE, EC_TIMEOUTEEP, EC_TIMEOUTRET, ECT_REG_ALIAS, ECT_REG_STADR, ECT_SII_ID, ECT_SII_MANUF, ECT_SII_REV, and htoes.