sc_somanet-base: app_linux_fwupdate/src/slaveinfo.c File Reference
slaveinfo.c File Reference
Example code for Simple Open EtherCAT master.
#include <stdio.h>
#include <string.h>
#include "ethercattype.h"
#include "nicdrv.h"
#include "ethercatbase.h"
#include "ethercatmain.h"
#include "ethercatconfig.h"
#include "ethercatcoe.h"
#include "ethercatdc.h"
#include "ethercatprint.h"
Functions
char * SDO2string (uint16 slave, uint16 index, uint8 subidx, uint16 dtype)
void slaveinfo (char *ifname)
int main (int argc, char *argv[])
Variables
char IOmap [4096]
ec_ODlistt ODlist
ec_OElistt OElist
boolean printSDO = FALSE
char usdo [128]
char hstr [1024]
Detailed Description
Example code for Simple Open EtherCAT master.
Usage : slaveinfo [ifname] [-sdo] Ifname is NIC interface, f.e. eth0. Optional -sdo to display CoE object dictionary.
This shows the configured slave data.
(c)Arthur Ketels 2010 - 2011
Definition in file slaveinfo.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 278 of file slaveinfo.c.
References printSDO, slaveinfo(), and TRUE.
char* SDO2string (uint16 slave, uint16 index, uint8 subidx, uint16 dtype)
Definition at line 32 of file slaveinfo.c.
References ec_elist2string(), ec_SDOread(), EC_TIMEOUTRXM, EcatError, ECT_BIT1, ECT_BIT2, ECT_BIT3, ECT_BIT4, ECT_BIT5, ECT_BIT6, ECT_BIT7, ECT_BIT8, ECT_BOOLEAN, ECT_INTEGER16, ECT_INTEGER24, ECT_INTEGER32, ECT_INTEGER64, ECT_INTEGER8, ECT_OCTET_STRING, ECT_REAL32, ECT_REAL64, ECT_UNSIGNED16, ECT_UNSIGNED24, ECT_UNSIGNED32, ECT_UNSIGNED64, ECT_UNSIGNED8, ECT_VISIBLE_STRING, FALSE, hstr, and usdo.
Referenced by slaveinfo().
void slaveinfo (char * ifname)
Definition at line 133 of file slaveinfo.c.
References ec_OElistt::BitLength, ec_slavet::blockLRW, ec_slavet::CoEdetails, ec_ODlistt::DataType, ec_OElistt::DataType, ec_slavet::Ebuscurrent, ec_ALstatuscode2string(), ec_close(), ec_config(), ec_configdc(), ec_elist2string(), ec_group, ec_init(), EC_MAXSM, ec_readODdescription(), ec_readODlist(), ec_readOE(), ec_readstate(), ec_siifind(), ec_siigetbyte(), ec_slave, ec_slavecount, EC_STATE_SAFE_OP, ec_statecheck(), EC_TIMEOUTSTATE, EcatError, ECT_SII_GENERAL, ec_ODlistt::Entries, ec_slavet::EoEdetails, FALSE, ec_slavet::FMMUunused, ec_slavet::FoEdetails, ec_ODlistt::Index, IOmap, ec_ODlistt::MaxSub, ec_ODlistt::Name, ec_OElistt::Name, ec_OElistt::ObjAccess, ec_ODlistt::ObjectCode, printSDO, SDO2string(), and ec_slavet::SoEdetails.
Referenced by main().
Variable Documentation
char hstr[1024]
Definition at line 30 of file slaveinfo.c.
Referenced by SDO2string().
char IOmap[4096]
Definition at line 25 of file slaveinfo.c.
Referenced by slaveinfo().
ec_ODlistt ODlist
Definition at line 26 of file slaveinfo.c.
ec_OElistt OElist
Definition at line 27 of file slaveinfo.c.
boolean printSDO = FALSE
Definition at line 28 of file slaveinfo.c.
Referenced by main(), and slaveinfo().
char usdo[128]
Definition at line 29 of file slaveinfo.c.
Referenced by SDO2string().