sc_somanet-base: app_linux_fwupdate/src/ethercatfoe.c File Reference
ethercatfoe.c File Reference
File over EtherCAT (FoE) module.
#include <stdio.h>
#include <string.h>
#include <sys/time.h>
#include <unistd.h>
#include "ethercattype.h"
#include "nicdrv.h"
#include "ethercatbase.h"
#include "ethercatmain.h"
#include "ethercatfoe.h"
Data Structures
struct PACKED
Macros
#define EC_MAXFOEDATA 512
Typedefs
typedef struct PACKED ec_FOEt
Functions
int ec_FOEread (uint16 slave, char *filename, uint32 password, int *psize, void *p, int timeout)
int ec_FOEwrite (uint16 slave, char *filename, uint32 password, int psize, void *p, int timeout)
Detailed Description
File over EtherCAT (FoE) module.
SDO read / write and SDO service functions
Definition in file ethercatfoe.c.
Macro Definition Documentation
#define EC_MAXFOEDATA 512
Definition at line 60 of file ethercatfoe.c.
Typedef Documentation
typedef struct PACKED ec_FOEt
FOE structure. Used for Read, Write, Data, Ack and Error mailbox packets.
Function Documentation
int ec_FOEread (uint16 slave, char * filename, uint32 password, int * psize, void * p, int timeout)
FoE read, blocking.
Parameters
[in] slave = Slave number.
[in] filename = Filename of file to read.
[in] password = password.
[in,out] psize = Size in bytes of file buffer, returns bytes read from file.
[out] p = Pointer to file buffer
[in] timeout = Timeout in us, standard is EC_TIMEOUTRXM
Returns
Workcounter from last slave response
Definition at line 94 of file ethercatfoe.c.
References PACKED::address, PACKED::Data, ec_clearmbx(), EC_ERR_TYPE_FOE_BUF2SMALL, EC_ERR_TYPE_FOE_ERROR, EC_ERR_TYPE_PACKET_ERROR, ec_mbxreceive(), ec_mbxsend(), ec_nextmbxcnt(), ec_slave, EC_TIMEOUTTXM, ECT_FOE_ACK, ECT_FOE_DATA, ECT_FOE_ERROR, ECT_FOE_READ, ECT_MBXT_FOE, etohl, etohs, FALSE, PACKED::FileName, htoel, htoes, PACKED::length, ec_slavet::mbx_cnt, ec_slavet::mbx_l, PACKED::MbxHeader, PACKED::mbxtype, PACKED::OpCode, PACKED::PacketNumber, PACKED::Password, PACKED::priority, and TRUE.
int ec_FOEwrite (uint16 slave, char * filename, uint32 password, int psize, void * p, int timeout)
FoE write, blocking.
Parameters
[in] slave = Slave number.
[in] filename = Filename of file to write.
[in] password = password.
[in] psize = Size in bytes of file buffer.
[out] p = Pointer to file buffer
[in] timeout = Timeout in us, standard is EC_TIMEOUTRXM
Returns
Workcounter from last slave response
Definition at line 211 of file ethercatfoe.c.
References PACKED::address, PACKED::Data, ec_clearmbx(), EC_ERR_TYPE_FOE_ERROR, EC_ERR_TYPE_FOE_PACKETNUMBER, EC_ERR_TYPE_PACKET_ERROR, ec_mbxreceive(), ec_mbxsend(), ec_nextmbxcnt(), ec_slave, EC_TIMEOUTTXM, ECT_FOE_ACK, ECT_FOE_DATA, ECT_FOE_ERROR, ECT_FOE_WRITE, ECT_MBXT_FOE, etohl, FALSE, PACKED::FileName, htoel, htoes, PACKED::length, ec_slavet::mbx_cnt, ec_slavet::mbx_l, PACKED::MbxHeader, PACKED::mbxtype, PACKED::OpCode, PACKED::PacketNumber, PACKED::Password, PACKED::priority, and TRUE.
Referenced by end_file(), slave_testfoe(), and start_file().