sc_somanet-base: module_fwupdate/device_access.h File Reference
device_access.h File Reference
#include <xs1.h>
#include "flashlib.h"
Functions
int fl_int_spiMasterInit (void)
int fl_int_spiInit (int div)
unsigned int fl_int_issueShortCommand (unsigned char cmd, unsigned int addr, unsigned int addrSize, unsigned int dummySize, unsigned int dataSize)
void fl_int_waitWhileWriting (const fl_DeviceSpec *flashAccess)
int fl_int_programPageAsync (const fl_DeviceSpec *flashAccess, unsigned int pageAddress, const unsigned char data[])
int fl_int_programPage (const fl_DeviceSpec *flashAccess, unsigned int pageAddress, const unsigned char data[])
int fl_int_readPage (const fl_DeviceSpec *flashAccess, unsigned int pageAddress, unsigned char data[])
int fl_int_readBytes (const fl_DeviceSpec *flashAccess, unsigned address, unsigned char data[], unsigned numBytes)
int fl_int_getBusyStatus (const fl_DeviceSpec *flashAccess)
unsigned fl_int_getFullStatus (const fl_DeviceSpec *flashAccess)
Function Documentation
int fl_int_getBusyStatus (const fl_DeviceSpec * flashAccess)
Referenced by fl_getBusyStatus().
unsigned fl_int_getFullStatus (const fl_DeviceSpec * flashAccess)
Referenced by fl_getFullStatus().
unsigned int fl_int_issueShortCommand (unsigned char cmd, unsigned int addr, unsigned int addrSize, unsigned int dummySize, unsigned int dataSize)
Definition at line 92 of file device_access.xc.
References g_portHolder.
Referenced by fl_connectToDevice(), fl_int_getBusyStatus(), fl_int_getFullStatus(), fl_int_programPageAsync(), fl_setProtection(), fl_setSectorProtection(), and fl_setWritability().
int fl_int_programPage (const fl_DeviceSpec * flashAccess, unsigned int pageAddress, const unsigned char data[])
int fl_int_programPageAsync (const fl_DeviceSpec * flashAccess, unsigned int pageAddress, const unsigned char data[])
int fl_int_readBytes (const fl_DeviceSpec * flashAccess, unsigned address, unsigned char data[], unsigned numBytes)
Referenced by fl_connectToDevice(), fl_getFactoryImage(), fl_getFlashIdNum(), fl_getFlashIdStr(), fl_getNextBootImage(), fl_readData(), fl_readPage(), and fl_writeData().
int fl_int_readPage (const fl_DeviceSpec * flashAccess, unsigned int pageAddress, unsigned char data[])
int fl_int_spiInit (int div)
Definition at line 51 of file device_access.xc.
References g_portHolder.
Referenced by fl_connectToDevice().
int fl_int_spiMasterInit (void)
Definition at line 46 of file device_access.xc.
Referenced by fl_connectToDevice().
void fl_int_waitWhileWriting (const fl_DeviceSpec * flashAccess)
Referenced by fl_endWriteImage(), fl_eraseSector(), fl_setProtection(), fl_setSectorProtection(), fl_startImageReplace(), fl_writeImagePage(), and fl_writePage().