sc_sncn_ethercat: app_linux_fwupdate/src/ethercatdc.c File Reference
ethercatdc.c File Reference
Distributed Clock EtherCAT functions.
#include "ethercattype.h"
#include "nicdrv.h"
#include "ethercatbase.h"
#include "ethercatmain.h"
#include "ethercatdc.h"
Macros
#define PORTM0 0x01
#define PORTM1 0x02
#define PORTM2 0x04
#define PORTM3 0x08
#define SyncDelay ((int32)100000000)
Functions
void ec_dcsync0 (uint16 slave, boolean act, uint32 CyclTime, uint32 CyclShift)
void ec_dcsync01 (uint16 slave, boolean act, uint32 CyclTime0, uint32 CyclTime1, uint32 CyclShift)
int32 ec_porttime (uint16 slave, uint8 port)
uint8 ec_prevport (uint16 slave, uint8 port)
uint8 ec_parentport (uint16 parent)
boolean ec_configdc (void)
Detailed Description
Distributed Clock EtherCAT functions.
Definition in file ethercatdc.c.
Macro Definition Documentation
#define PORTM0 0x01
Definition at line 52 of file ethercatdc.c.
Referenced by ec_configdc(), ec_parentport(), and ec_prevport().
#define PORTM1 0x02
Definition at line 53 of file ethercatdc.c.
Referenced by ec_configdc(), ec_parentport(), and ec_prevport().
#define PORTM2 0x04
Definition at line 54 of file ethercatdc.c.
Referenced by ec_configdc(), ec_parentport(), and ec_prevport().
#define PORTM3 0x08
Definition at line 55 of file ethercatdc.c.
Referenced by ec_configdc(), ec_parentport(), and ec_prevport().
#define SyncDelay ((int32)100000000)
1st sync pulse delay in ns here 100ms
Definition at line 58 of file ethercatdc.c.
Referenced by ec_dcsync0(), and ec_dcsync01().
Function Documentation
boolean ec_configdc (void)
Locate DC slaves, measure propagation delays.
return boolean if slaves are found with DC
Definition at line 266 of file ethercatdc.c.
References ec_slavet::activeports, ec_slavet::configadr, ec_slavet::consumedports, ec_slavet::DCnext, ec_groupt::DCnext, ec_slavet::DCprevious, ec_slavet::DCrtA, ec_slavet::DCrtB, ec_slavet::DCrtC, ec_slavet::DCrtD, ec_BWR(), ec_FPRD(), ec_FPWR(), ec_group, ec_parentport(), ec_porttime(), ec_prevport(), ec_slave, ec_slavecount, EC_TIMEOUTRET, ECT_REG_DCSOF, ECT_REG_DCSYSDELAY, ECT_REG_DCSYSOFFSET, ECT_REG_DCTIME0, ECT_REG_DCTIME1, ECT_REG_DCTIME2, ECT_REG_DCTIME3, ec_slavet::entryport, etohl, etohll, FALSE, ec_slavet::hasdc, ec_groupt::hasdc, htoel, htoell, ec_slavet::parent, ec_slavet::parentport, ec_slavet::pdelay, PORTM0, PORTM1, PORTM2, PORTM3, and TRUE.
Referenced by slaveinfo().
void ec_dcsync0 (uint16 slave, boolean act, uint32 CyclTime, uint32 CyclShift)
Set DC of slave to fire sync0 at CyclTime interval with CyclShift offset.
Parameters
[in] slave Slave number.
[in] act TRUE = active, FALSE = deactivated
[in] CyclTime Cycltime in ns.
[in] CyclShift CyclShift in ns.
Definition at line 68 of file ethercatdc.c.
References ec_slavet::configadr, ec_FPRD(), ec_FPWR(), ec_slave, EC_TIMEOUTRET, ECT_REG_DCCUC, ECT_REG_DCCYCLE0, ECT_REG_DCSTART0, ECT_REG_DCSYNCACT, ECT_REG_DCSYSTIME, etohll, htoel, htoell, and SyncDelay.
void ec_dcsync01 (uint16 slave, boolean act, uint32 CyclTime0, uint32 CyclTime1, uint32 CyclShift)
Set DC of slave to fire sync0 and sync1 at CyclTime interval with CyclShift offset.
Parameters
[in] slave Slave number.
[in] act TRUE = active, FALSE = deactivated
[in] CyclTime0 Cycltime SYNC0 in ns.
[in] CyclTime1 Cycltime SYNC1 in ns. This time is a delta time in relation to the SYNC0 fire. If CylcTime1 = 0 then SYNC1 fires a the same time as SYNC0.
[in] CyclShift CyclShift in ns.
Definition at line 120 of file ethercatdc.c.
References ec_slavet::configadr, ec_FPRD(), ec_FPWR(), ec_slave, EC_TIMEOUTRET, ECT_REG_DCCUC, ECT_REG_DCCYCLE0, ECT_REG_DCCYCLE1, ECT_REG_DCSTART0, ECT_REG_DCSYNCACT, ECT_REG_DCSYSTIME, etohll, htoel, htoell, and SyncDelay.
uint8 ec_parentport (uint16 parent)
Definition at line 231 of file ethercatdc.c.
References ec_slavet::consumedports, ec_slave, PORTM0, PORTM1, PORTM2, and PORTM3.
Referenced by ec_configdc().
int32 ec_porttime (uint16 slave, uint8 port)
Definition at line 164 of file ethercatdc.c.
References ec_slavet::DCrtA, ec_slavet::DCrtB, ec_slavet::DCrtC, ec_slavet::DCrtD, and ec_slave.
Referenced by ec_configdc().
uint8 ec_prevport (uint16 slave, uint8 port)
Definition at line 188 of file ethercatdc.c.
References ec_slavet::activeports, ec_slave, PORTM0, PORTM1, PORTM2, and PORTM3.
Referenced by ec_configdc().