sc_somanet-base: module_fwupdate/flashlib.c File Reference
flashlib.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <xclib.h>
#include <flashlib.h>
#include "device_access.h"
#include "spec_definitions.h"
#include <print.h>
Data Structures
struct fl_ImageWriteState
struct fl_ImageReadState
Macros
#define IMAGETAG (0x1a551e5)
#define MAX_PAGE_SIZE 256
#define VALIDATE
Functions
int fl_connect (fl_SPIPorts *pHolder)
int fl_connectToDevice (fl_SPIPorts *pHolder, const fl_DeviceSpec *deviceSpecPtr, unsigned int specCount)
int fl_disconnect ()
int fl_getFlashIdNum ()
int fl_getFlashIdStr (char buf[], int maxlen)
int fl_getBusyStatus ()
unsigned int fl_getFullStatus ()
int fl_getFlashType ()
unsigned fl_getFlashSize ()
int fl_eraseAll ()
int fl_setWritability (int enable)
int fl_setProtection (int protect)
int fl_getNumSectors ()
int fl_getSectorSize (int sectorNum)
int fl_getSectorAddress (int sectorNum)
int fl_eraseSector (int sectorNum)
int fl_setSectorProtection (int sectorNum, int protect)
unsigned fl_getNumDataSectors (void)
unsigned fl_getDataSectorSize (unsigned n)
int fl_eraseDataSector (unsigned n)
int fl_eraseAllDataSectors (void)
unsigned fl_getNumPages ()
unsigned fl_getPageSize ()
int fl_writePage (unsigned int address, const unsigned char data[])
int fl_readPage (unsigned int address, unsigned char data[])
unsigned fl_getNumDataPages (void)
int fl_writeDataPage (unsigned n, const unsigned char data[])
int fl_readDataPage (unsigned n, unsigned char dst[])
unsigned int fl_setBootPartitionSize (unsigned int s)
unsigned int fl_getBootPartitionSize ()
unsigned int fl_getDataPartitionBase ()
unsigned int fl_getDataPartitionSize ()
int fl_getFactoryImage (fl_BootImageInfo *bootImageInfo)
int fl_getNextBootImage (fl_BootImageInfo *bootImageInfo)
int fl_eraseNextBootImage (fl_BootImageInfo *bootImageInfo)
unsigned fl_getImageVersion (fl_BootImageInfo *bootImageInfo)
int fl_startImageAdd (fl_BootImageInfo *bootImageInfo, unsigned maxsize, unsigned padding)
int fl_startImageAddAt (unsigned offset, unsigned maxsize)
int fl_startImageReplace (fl_BootImageInfo *bootImageInfo, unsigned maxsize)
int fl_writeImagePage (const unsigned char page[])
int fl_endWriteImage (void)
int fl_deleteImage (fl_BootImageInfo *bootImageInfo)
int fl_addBootImage (fl_BootImageInfo *bootImageInfo, unsigned imageSize, unsigned(*getData)(void *, unsigned, unsigned char *), void *userPtr)
int fl_startImageRead (fl_BootImageInfo *bootImageInfo)
int fl_readData (unsigned offset, unsigned size, unsigned char dst[])
unsigned fl_getWriteScratchSize (unsigned int offset, unsigned int size)
int fl_writeData (unsigned int offset, unsigned int size, const unsigned char src[], unsigned char buffer[])
int fl_int_copySpec (fl_DeviceSpec *dest)
Variables
fl_SPIPorts g_portHolder
Detailed Description
Copyright (c) 2014, Synapticon GmbH & XMOS Ltd All rights reserved. Author: Pavan Kanajar pkana.nosp@m.jar@.nosp@m.synap.nosp@m.tico.nosp@m.n.com
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Execution of this software or parts of it exclusively takes place on hardware produced by Synapticon GmbH.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Synapticon GmbH.
Definition in file flashlib.c.
Macro Definition Documentation
#define IMAGETAG (0x1a551e5)
Definition at line 47 of file flashlib.c.
Referenced by fl_getFactoryImage(), and fl_getNextBootImage().
#define MAX_PAGE_SIZE 256
Definition at line 49 of file flashlib.c.
Referenced by fl_addBootImage(), and fl_writeImagePage().
#define VALIDATE
Definition at line 786 of file flashlib.c.
Function Documentation
int fl_addBootImage (fl_BootImageInfo * bootImageInfo, unsigned imageSize, unsigned(*)(void *, unsigned, unsigned char *) getData, void * userPtr)
Definition at line 827 of file flashlib.c.
References fl_endWriteImage(), fl_getPageSize(), fl_startImageAdd(), fl_writeImagePage(), and MAX_PAGE_SIZE.
int fl_connect (fl_SPIPorts * pHolder)
Definition at line 67 of file flashlib.c.
References fl_connectToDevice().
Referenced by flash_connect().
int fl_connectToDevice (fl_SPIPorts * pHolder, const fl_DeviceSpec * deviceSpecPtr, unsigned int specCount)
Definition at line 73 of file flashlib.c.
References fl_getFlashSize(), fl_int_issueShortCommand(), fl_int_readBytes(), fl_int_spiInit(), fl_int_spiMasterInit(), fl_setBootPartitionSize(), and g_portHolder.
Referenced by fl_connect().
int fl_deleteImage (fl_BootImageInfo * bootImageInfo)
Definition at line 815 of file flashlib.c.
References fl_eraseSector().
Referenced by fl_eraseNextBootImage().
int fl_disconnect ()
Definition at line 109 of file flashlib.c.
int fl_endWriteImage (void)
Definition at line 808 of file flashlib.c.
References fl_int_waitWhileWriting(), and fl_setWritability().
Referenced by fl_addBootImage(), and flash_buf_end().
int fl_eraseAll ()
Definition at line 203 of file flashlib.c.
References fl_eraseSector(), and fl_getNumSectors().
Referenced by flash_erase().
int fl_eraseAllDataSectors (void)
Definition at line 432 of file flashlib.c.
References fl_eraseSector(), fl_getDataPartitionBase(), and fl_getNumSectors().
int fl_eraseDataSector (unsigned n)
Definition at line 422 of file flashlib.c.
References fl_eraseSector(), fl_getDataPartitionBase(), and fl_getNumSectors().
int fl_eraseNextBootImage (fl_BootImageInfo * bootImageInfo)
Definition at line 609 of file flashlib.c.
References fl_deleteImage(), and fl_getNextBootImage().
int fl_eraseSector (int sectorNum)
Definition at line 382 of file flashlib.c.
References fl_int_waitWhileWriting(), and fl_setWritability().
Referenced by fl_deleteImage(), fl_eraseAll(), fl_eraseAllDataSectors(), fl_eraseDataSector(), and fl_writeData().
unsigned int fl_getBootPartitionSize ()
Definition at line 541 of file flashlib.c.
References fl_getFlashSize().
Referenced by fl_getDataPartitionBase(), and fl_getDataPartitionSize().
int fl_getBusyStatus ()
Definition at line 172 of file flashlib.c.
References fl_int_getBusyStatus().
unsigned int fl_getDataPartitionBase ()
Definition at line 547 of file flashlib.c.
References fl_getBootPartitionSize().
Referenced by fl_eraseAllDataSectors(), fl_eraseDataSector(), fl_getDataSectorSize(), fl_getNumDataSectors(), fl_getWriteScratchSize(), fl_readData(), fl_readDataPage(), fl_writeData(), and fl_writeDataPage().
unsigned int fl_getDataPartitionSize ()
Definition at line 552 of file flashlib.c.
References fl_getBootPartitionSize(), and fl_getFlashSize().
Referenced by fl_getNumDataPages().
unsigned fl_getDataSectorSize (unsigned n)
Definition at line 413 of file flashlib.c.
References fl_getDataPartitionBase(), and fl_getSectorSize().
int fl_getFactoryImage (fl_BootImageInfo * bootImageInfo)
Definition at line 564 of file flashlib.c.
References fl_int_readBytes(), and IMAGETAG.
Referenced by fl_startImageAddAt().
int fl_getFlashIdNum ()
Definition at line 114 of file flashlib.c.
References fl_int_readBytes().
int fl_getFlashIdStr (char buf[], int maxlen)
Definition at line 128 of file flashlib.c.
References fl_int_readBytes().
unsigned fl_getFlashSize ()
Definition at line 193 of file flashlib.c.
Referenced by fl_connectToDevice(), fl_getBootPartitionSize(), fl_getDataPartitionSize(), fl_getNumSectors(), and fl_setBootPartitionSize().
int fl_getFlashType ()
Definition at line 187 of file flashlib.c.
unsigned int fl_getFullStatus ()
Definition at line 177 of file flashlib.c.
References fl_int_getFullStatus().
unsigned fl_getImageVersion (fl_BootImageInfo * bootImageInfo)
Definition at line 703 of file flashlib.c.
int fl_getNextBootImage (fl_BootImageInfo * bootImageInfo)
Definition at line 585 of file flashlib.c.
References fl_getNumSectors(), fl_getSectorAddress(), fl_int_readBytes(), and IMAGETAG.
Referenced by fl_eraseNextBootImage().
unsigned fl_getNumDataPages (void)
Definition at line 485 of file flashlib.c.
References fl_getDataPartitionSize(), and fl_getPageSize().
Referenced by fl_readDataPage(), and fl_writeDataPage().
unsigned fl_getNumDataSectors (void)
Definition at line 405 of file flashlib.c.
References fl_getDataPartitionBase(), and fl_getNumSectors().
unsigned fl_getNumPages ()
Definition at line 449 of file flashlib.c.
int fl_getNumSectors ()
Definition at line 293 of file flashlib.c.
References fl_getFlashSize().
Referenced by fl_eraseAll(), fl_eraseAllDataSectors(), fl_eraseDataSector(), fl_getNextBootImage(), fl_getNumDataSectors(), fl_getWriteScratchSize(), fl_setBootPartitionSize(), fl_setProtection(), and fl_writeData().
unsigned fl_getPageSize ()
Definition at line 455 of file flashlib.c.
Referenced by fl_addBootImage(), fl_getNumDataPages(), fl_getSectorAddress(), fl_getSectorSize(), fl_int_programPageAsync(), fl_readDataPage(), fl_readPage(), fl_startImageRead(), fl_writeData(), fl_writeDataPage(), and fl_writeImagePage().
int fl_getSectorAddress (int sectorNum)
Definition at line 327 of file flashlib.c.
References fl_getPageSize().
Referenced by fl_getNextBootImage(), fl_getWriteScratchSize(), fl_setBootPartitionSize(), fl_setSectorProtection(), fl_startImageAddAt(), and fl_writeData().
int fl_getSectorSize (int sectorNum)
Definition at line 309 of file flashlib.c.
References fl_getPageSize().
Referenced by fl_getDataSectorSize(), fl_getWriteScratchSize(), and fl_writeData().
unsigned fl_getWriteScratchSize (unsigned int offset, unsigned int size)
Definition at line 909 of file flashlib.c.
References fl_getDataPartitionBase(), fl_getNumSectors(), fl_getSectorAddress(), and fl_getSectorSize().
int fl_int_copySpec (fl_DeviceSpec * dest)
Definition at line 980 of file flashlib.c.
int fl_readData (unsigned offset, unsigned size, unsigned char dst[])
Definition at line 902 of file flashlib.c.
References fl_getDataPartitionBase(), and fl_int_readBytes().
int fl_readDataPage (unsigned n, unsigned char dst[])
Definition at line 498 of file flashlib.c.
References fl_getDataPartitionBase(), fl_getNumDataPages(), fl_getPageSize(), and fl_readPage().
int fl_readPage (unsigned int address, unsigned char data[])
Definition at line 480 of file flashlib.c.
References fl_getPageSize(), and fl_int_readBytes().
Referenced by fl_readDataPage(), and fl_writeImagePage().
unsigned int fl_setBootPartitionSize (unsigned int s)
Definition at line 516 of file flashlib.c.
References fl_getFlashSize(), fl_getNumSectors(), and fl_getSectorAddress().
Referenced by fl_connectToDevice().
int fl_setProtection (int protect)
Definition at line 250 of file flashlib.c.
References fl_getNumSectors(), fl_int_issueShortCommand(), fl_int_waitWhileWriting(), fl_setSectorProtection(), and fl_setWritability().
Referenced by flash_setup().
int fl_setSectorProtection (int sectorNum, int protect)
Definition at line 391 of file flashlib.c.
References fl_getSectorAddress(), fl_int_issueShortCommand(), fl_int_waitWhileWriting(), and fl_setWritability().
Referenced by fl_setProtection().
int fl_setWritability (int enable)
Definition at line 215 of file flashlib.c.
References fl_int_issueShortCommand().
Referenced by fl_endWriteImage(), fl_eraseSector(), fl_setProtection(), fl_setSectorProtection(), and fl_writePage().
int fl_startImageAdd (fl_BootImageInfo * bootImageInfo, unsigned maxsize, unsigned padding)
Definition at line 724 of file flashlib.c.
References fl_ImageWriteState::eraseSector.
Referenced by fl_addBootImage().
int fl_startImageAddAt (unsigned offset, unsigned maxsize)
Definition at line 735 of file flashlib.c.
References fl_ImageWriteState::eraseSector, fl_getFactoryImage(), and fl_getSectorAddress().
int fl_startImageRead (fl_BootImageInfo * bootImageInfo)
Definition at line 877 of file flashlib.c.
References fl_ImageReadState::currentAddress, fl_getPageSize(), and fl_ImageReadState::limitAddress.
int fl_startImageReplace (fl_BootImageInfo * bootImageInfo, unsigned maxsize)
Definition at line 763 of file flashlib.c.
References fl_ImageWriteState::eraseSector, fl_int_waitWhileWriting(), and fl_ImageWriteState::limitAddress.
int fl_writeData (unsigned int offset, unsigned int size, const unsigned char src[], unsigned char buffer[])
Definition at line 931 of file flashlib.c.
References fl_eraseSector(), fl_getDataPartitionBase(), fl_getNumSectors(), fl_getPageSize(), fl_getSectorAddress(), fl_getSectorSize(), fl_int_readBytes(), and fl_writePage().
int fl_writeDataPage (unsigned n, const unsigned char data[])
Definition at line 490 of file flashlib.c.
References fl_getDataPartitionBase(), fl_getNumDataPages(), fl_getPageSize(), and fl_writePage().
int fl_writeImagePage (const unsigned char page[])
Definition at line 788 of file flashlib.c.
References fl_ImageWriteState::currentAddress, fl_getPageSize(), fl_int_waitWhileWriting(), fl_readPage(), fl_writePage(), fl_ImageWriteState::limitAddress, and MAX_PAGE_SIZE.
Referenced by fl_addBootImage().
int fl_writePage (unsigned int address, const unsigned char data[])
Definition at line 471 of file flashlib.c.
References fl_int_waitWhileWriting(), and fl_setWritability().
Referenced by fl_writeData(), fl_writeDataPage(), fl_writeImagePage(), and flash_buffer().
Variable Documentation
fl_SPIPorts g_portHolder
Definition at line 62 of file flashlib.c.
Referenced by fl_connectToDevice(), fl_int_issueShortCommand(), fl_int_programPageAsync(), fl_int_readBytes(), and fl_int_spiInit().